--
-- ER/Studio 8.0 SQL Code Generation
-- Company :      UNAM
-- Project :      magestic-en.DM1
-- Author :       mauri33445@live.com.mx
--
-- Date Created : Monday, May 23, 2022 16:10:58
-- Target DBMS : Oracle 11g
--

DROP TABLE ACTIVITY CASCADE CONSTRAINTS
;
DROP TABLE ACTIVITY_CATALOGUE CASCADE CONSTRAINTS
;
DROP TABLE ACTIVITY_EVALUATION CASCADE CONSTRAINTS
;
DROP TABLE ADMINISTRATOR CASCADE CONSTRAINTS
;
DROP TABLE CAREER CASCADE CONSTRAINTS
;
DROP TABLE CATEGORY CASCADE CONSTRAINTS
;
DROP TABLE DEPARTMENT CASCADE CONSTRAINTS
;
DROP TABLE DIPLOMA CASCADE CONSTRAINTS
;
DROP TABLE DIVISION CASCADE CONSTRAINTS
;
DROP TABLE FACULTY CASCADE CONSTRAINTS
;
DROP TABLE INSTRUCTOR CASCADE CONSTRAINTS
;
DROP TABLE INSTRUCTOR_EVALUATION CASCADE CONSTRAINTS
;
DROP TABLE PARTICIPANT CASCADE CONSTRAINTS
;
DROP TABLE PROFESSOR CASCADE CONSTRAINTS
;
DROP TABLE PROFESSOR_CAREER CASCADE CONSTRAINTS
;
DROP TABLE PROFESSOR_CATEGORY CASCADE CONSTRAINTS
;
DROP TABLE PROFESSOR_DIVISION CASCADE CONSTRAINTS
;
DROP TABLE PROFESSOR_FACULTY CASCADE CONSTRAINTS
;
DROP TABLE SEMINAR_TOPIC CASCADE CONSTRAINTS
;
DROP TABLE USER CASCADE CONSTRAINTS
;
DROP TABLE VENUE CASCADE CONSTRAINTS
;
-- 
-- TABLE: ACTIVITY 
--

CREATE TABLE ACTIVITY(
    ACTIVITY_ID              NUMBER(40, 0)    NOT NULL,
    SEM_YEAR                 NUMBER(4, 0)     NOT NULL,
    SEM_NUM                  NUMBER(1, 0)     NOT NULL,
    SEM_TYPE                 NUMBER(1, 0)     NOT NULL,
    START_DATE               DATE             NOT NULL,
    END_DATE                 VARCHAR2(40)     NOT NULL,
    MANUAL_DATE              VARCHAR2(200)    NOT NULL,
    DAY                      VARCHAR2(12)     NOT NULL,
    CTC                      NUMBER(2, 0),
    COST                     NUMBER(10, 2)    NOT NULL,
    MAX_QUOTA                NUMBER(5, 0)     NOT NULL,
    MIN_QUOTA                NUMBER(5, 0)     NOT NULL,
    VENUE_ID                 NUMBER(20, 0)    NOT NULL,
    ACTIVITY_CATALOGUE_ID    NUMBER(40, 0)    NOT NULL,
    CONSTRAINT PK4 PRIMARY KEY (ACTIVITY_ID)
)
;



-- 
-- TABLE: ACTIVITY_CATALOGUE 
--

CREATE TABLE ACTIVITY_CATALOGUE(
    ACTIVITY_CATALOGUE_ID    NUMBER(40, 0)     NOT NULL,
    KEY                      VARCHAR2(30)      NOT NULL,
    NAME                     VARCHAR2(300)     NOT NULL,
    HOURS                    NUMBER(3, 0)      NOT NULL,
    TYPE                     VARCHAR2(2)       NOT NULL,
    INSTITUTION              VARCHAR2(10),
    AIMED_AT                 VARCHAR2(500),
    OBJECTIVE                VARCHAR2(500),
    CONTENT                  VARCHAR2(2000),
    BACKGROUND               VARCHAR2(500),
    CREATION_DATE            DATE              NOT NULL,
    MODULE                   NUMBER(10, 0),
    DEPARTMENT_ID            NUMBER(10, 0)     NOT NULL,
    DIPLOMA_ID               NUMBER(20, 0),
    CONSTRAINT PK3 PRIMARY KEY (ACTIVITY_CATALOGUE_ID)
)
;



-- 
-- TABLE: ACTIVITY_EVALUATION 
--

CREATE TABLE ACTIVITY_EVALUATION(
    ACTIVITY_EVALUATION_ID    NUMBER(40, 0)    NOT NULL,
    QUESTION_1_1              NUMBER(2, 0),
    QUESTION_1_2              NUMBER(2, 0),
    QUESTION_1_3              NUMBER(2, 0),
    QUESTION_1_4              NUMBER(2, 0),
    QUESTION_1_5              NUMBER(2, 0),
    QUESTION_2_1              NUMBER(2, 0),
    QUESTION_2_2              NUMBER(2, 0),
    QUESTION_2_3              NUMBER(2, 0),
    QUESTION_2_4              NUMBER(2, 0),
    QUESTION_3_1              NUMBER(2, 0),
    QUESTION_3_2              NUMBER(2, 0),
    QUESTION_3_3              NUMBER(2, 0),
    QUESTION_3_4              NUMBER(2, 0),
    QUESTION_4                NUMBER(1, 0),
    QUESTION_5                VARCHAR2(300),
    QUESTION_6                VARCHAR2(500),
    QUESTION_7                VARCHAR2(500),
    QUESTION_8                VARCHAR2(400),
    QUESTION_9                VARCHAR2(20),
    QUESTION_10               VARCHAR2(300),
    SEM_SCHEDULE              VARCHAR2(500),
    INT_SCHEDULE              VARCHAR2(500),
    PARTICIPANT_ID            NUMBER(40, 0)    NOT NULL,
    CONSTRAINT PK21 PRIMARY KEY (ACTIVITY_EVALUATION_ID)
)
;



-- 
-- TABLE: ADMINISTRATOR 
--

CREATE TABLE ADMINISTRATOR(
    ADMINISTRATOR_ID     NUMBER(10, 0)    NOT NULL,
    NAME                 VARCHAR2(100)    NOT NULL,
    LAST_NAME            VARCHAR2(40)     NOT NULL,
    MOTHERS_LAST_NAME    VARCHAR2(40),
    DEGREE               VARCHAR2(40),
    GENDER               VARCHAR2(1),
    JOB                  VARCHAR2(1)      NOT NULL,
    CONSTRAINT PK12 PRIMARY KEY (ADMINISTRATOR_ID)
)
;



-- 
-- TABLE: CAREER 
--

CREATE TABLE CAREER(
    CAREER_ID    NUMBER(10, 0)    NOT NULL,
    NAME         VARCHAR2(100)    NOT NULL,
    KEY          VARCHAR2(30)     NOT NULL,
    CONSTRAINT PK18 PRIMARY KEY (CAREER_ID)
)
;



-- 
-- TABLE: CATEGORY 
--

CREATE TABLE CATEGORY(
    CATEGORY_ID     NUMBER(10, 0)    NOT NULL,
    NAME            VARCHAR2(50)     NOT NULL,
    ABBREVIATION    VARCHAR2(20)     NOT NULL,
    CONSTRAINT PK5 PRIMARY KEY (CATEGORY_ID)
)
;



-- 
-- TABLE: DEPARTMENT 
--

CREATE TABLE DEPARTMENT(
    DEPARTMENT_ID       NUMBER(10, 0)    NOT NULL,
    ABBREVIATION        VARCHAR2(40)     NOT NULL,
    NAME                VARCHAR2(100)    NOT NULL,
    ADMINISTRATOR_ID    NUMBER(10, 0)    NOT NULL,
    CONSTRAINT PK1 PRIMARY KEY (DEPARTMENT_ID)
)
;



-- 
-- TABLE: DIPLOMA 
--

CREATE TABLE DIPLOMA(
    DIPLOMA_ID    NUMBER(20, 0)    NOT NULL,
    NAME          VARCHAR2(300)    NOT NULL,
    CONSTRAINT PK31 PRIMARY KEY (DIPLOMA_ID)
)
;



-- 
-- TABLE: DIVISION 
--

CREATE TABLE DIVISION(
    DIVISION_ID     NUMBER(10, 0)    NOT NULL,
    NAME            VARCHAR2(60)     NOT NULL,
    ABBREVIATION    VARCHAR2(30)     NOT NULL,
    CONSTRAINT PK16 PRIMARY KEY (DIVISION_ID)
)
;



-- 
-- TABLE: FACULTY 
--

CREATE TABLE FACULTY(
    FACULTY_ID    NUMBER(10, 0)    NOT NULL,
    NAME          VARCHAR2(50)     NOT NULL,
    CONSTRAINT PK15 PRIMARY KEY (FACULTY_ID)
)
;



-- 
-- TABLE: INSTRUCTOR 
--

CREATE TABLE INSTRUCTOR(
    INSTRUCTOR_ID    NUMBER(40, 0)    NOT NULL,
    KEY              VARCHAR2(10),
    SEND_DATE        DATE,
    PROFESSOR_ID     NUMBER(40, 0)    NOT NULL,
    ACTIVITY_ID      NUMBER(40, 0)    NOT NULL,
    CONSTRAINT PK6 PRIMARY KEY (INSTRUCTOR_ID)
)
;



-- 
-- TABLE: INSTRUCTOR_EVALUATION 
--

CREATE TABLE INSTRUCTOR_EVALUATION(
    INSTRUCTOR_EVALUATION_ID    NUMBER(40, 0)    NOT NULL,
    QUESTION_1                  NUMBER(2, 0),
    QUESTION_2                  NUMBER(2, 0),
    QUESTION_3                  NUMBER(2, 0),
    QUESTION_4                  NUMBER(2, 0),
    QUESTION_5                  NUMBER(2, 0),
    QUESTION_6                  NUMBER(2, 0),
    QUESTION_7                  NUMBER(2, 0),
    QUESTION_8                  NUMBER(2, 0),
    QUESTION_9                  NUMBER(2, 0),
    QUESTION_10                 NUMBER(2, 0),
    QUESTION_11                 NUMBER(2, 0),
    INSTRUCTOR_ID               NUMBER(40, 0)    NOT NULL,
    PARTICIPANT_ID              NUMBER(40, 0)    NOT NULL,
    CONSTRAINT PK22 PRIMARY KEY (INSTRUCTOR_EVALUATION_ID)
)
;



-- 
-- TABLE: PARTICIPANT 
--

CREATE TABLE PARTICIPANT(
    PARTICIPANT_ID    NUMBER(40, 0)    NOT NULL,
    ADDITIONAL        NUMBER(1, 0)     NOT NULL,
    ATTENDANCE        NUMBER(1, 0)     NOT NULL,
    ACCREDITED        VARCHAR2(40)     NOT NULL,
    CONFIRMATION      NUMBER(1, 0)     NOT NULL,
    CANCELED          NUMBER(1, 0)     NOT NULL,
    FREE              NUMBER(1, 0)     NOT NULL,
    DISCOUNT          NUMBER(4, 4)     NOT NULL,
    DEPOSIT           NUMBER(10, 2)    NOT NULL,
    WL_WAS            NUMBER(1, 0)     NOT NULL,
    WL_NUMBER         NUMBER,
    NAC               VARCHAR2(300),
    GRADE             NUMBER(2, 0),
    COMMENT           VARCHAR2(300),
    KEY               VARCHAR2(20),
    SEND_DATE         DATE,
    PROFESSOR_ID      NUMBER(40, 0)    NOT NULL,
    ACTIVITY_ID       NUMBER(40, 0)    NOT NULL,
    CONSTRAINT PK7 PRIMARY KEY (PARTICIPANT_ID)
)
;



-- 
-- TABLE: PROFESSOR 
--

CREATE TABLE PROFESSOR(
    PROFESSOR_ID         NUMBER(40, 0)    NOT NULL,
    NAME                 VARCHAR2(100)    NOT NULL,
    LAST_NAME            VARCHAR2(50)     NOT NULL,
    MOTHERS_LAST_NAME    VARCHAR2(50),
    RFC                  VARCHAR2(25),
    WORKER_NUMBER        VARCHAR2(30),
    BIRTHDATE            DATE,
    PHONE_NUMBER         VARCHAR2(15),
    DEGREE               VARCHAR2(40),
    EMAIL                VARCHAR2(40),
    GENDER               VARCHAR2(1),
    SEMBLANCE            VARCHAR2(200),
    FACEBOOK             VARCHAR2(40),
    IS_INSTRUCTOR        NUMBER(1, 0)     NOT NULL,
    IS_UNAM              NUMBER           NOT NULL,
    PROVENANCE           VARCHAR2(100),
    CONSTRAINT PK2 PRIMARY KEY (PROFESSOR_ID)
)
;



-- 
-- TABLE: PROFESSOR_CAREER 
--

CREATE TABLE PROFESSOR_CAREER(
    PROFESSOR_CAREER_ID    NUMBER(40, 0)    NOT NULL,
    CAREER_ID              NUMBER(10, 0)    NOT NULL,
    PROFESSOR_ID           NUMBER(40, 0)    NOT NULL,
    CONSTRAINT PK19 PRIMARY KEY (PROFESSOR_CAREER_ID)
)
;



-- 
-- TABLE: PROFESSOR_CATEGORY 
--

CREATE TABLE PROFESSOR_CATEGORY(
    PROFESSOR_CATEGORY_ID    NUMBER(40, 0)    NOT NULL,
    NUMBER                   NUMBER(1, 0)     NOT NULL,
    PROFESSOR_ID             NUMBER(40, 0)    NOT NULL,
    CATEGORY_ID              NUMBER(10, 0)    NOT NULL,
    CONSTRAINT PK14 PRIMARY KEY (PROFESSOR_CATEGORY_ID)
)
;



-- 
-- TABLE: PROFESSOR_DIVISION 
--

CREATE TABLE PROFESSOR_DIVISION(
    PROFESSOR_DIVISION_ID    NUMBER(40, 0)    NOT NULL,
    DIVISION_ID              NUMBER(10, 0)    NOT NULL,
    PROFESSOR_ID             NUMBER(40, 0)    NOT NULL,
    CONSTRAINT PK17 PRIMARY KEY (PROFESSOR_DIVISION_ID)
)
;



-- 
-- TABLE: PROFESSOR_FACULTY 
--

CREATE TABLE PROFESSOR_FACULTY(
    PROFESSOR_FACULTY_ID    VARCHAR2(40)     NOT NULL,
    PROFESSOR_ID            NUMBER(40, 0)    NOT NULL,
    FACULTY_ID              NUMBER(10, 0)    NOT NULL
)
;



-- 
-- TABLE: SEMINAR_TOPIC 
--

CREATE TABLE SEMINAR_TOPIC(
    SEMINAR_TOPIC_ID    VARCHAR2(40)     NOT NULL,
    NAME                VARCHAR2(300)    NOT NULL,
    HOURS               NUMBER(3, 0)     NOT NULL,
    EX_DATE             VARCHAR2(40)     NOT NULL,
    INSTRUCTOR_ID       NUMBER(40, 0)    NOT NULL,
    ACTIVITY_ID         NUMBER(40, 0)    NOT NULL,
    CONSTRAINT PK9 PRIMARY KEY (SEMINAR_TOPIC_ID)
)
;



-- 
-- TABLE: USER 
--

CREATE TABLE USER(
    USER_ID          NUMBER(40, 0)    NOT NULL,
    NAME             VARCHAR2(50)     NOT NULL,
    USERNAME         VARCHAR2(40)     NOT NULL,
    PASSWORD         VARCHAR2(40)     NOT NULL,
    ADMIN            NUMBER(1, 0)     NOT NULL,
    DEPARTMENT_ID    NUMBER(10, 0),
    CONSTRAINT PK23 PRIMARY KEY (USER_ID)
)
;



-- 
-- TABLE: VENUE 
--

CREATE TABLE VENUE(
    VENUE_ID    NUMBER(20, 0)    NOT NULL,
    NAME        VARCHAR2(100)    NOT NULL,
    CAPACITY    NUMBER(20, 0)    NOT NULL,
    LOCATION    VARCHAR2(200)    NOT NULL,
    CONSTRAINT PK20 PRIMARY KEY (VENUE_ID)
)
;



-- 
-- TABLE: ACTIVITY 
--

ALTER TABLE ACTIVITY ADD CONSTRAINT RefVENUE15 
    FOREIGN KEY (VENUE_ID)
    REFERENCES VENUE(VENUE_ID)
;

ALTER TABLE ACTIVITY ADD CONSTRAINT RefACTIVITY_CATALOGUE33 
    FOREIGN KEY (ACTIVITY_CATALOGUE_ID)
    REFERENCES ACTIVITY_CATALOGUE(ACTIVITY_CATALOGUE_ID)
;


-- 
-- TABLE: ACTIVITY_CATALOGUE 
--

ALTER TABLE ACTIVITY_CATALOGUE ADD CONSTRAINT RefDEPARTMENT14 
    FOREIGN KEY (DEPARTMENT_ID)
    REFERENCES DEPARTMENT(DEPARTMENT_ID)
;

ALTER TABLE ACTIVITY_CATALOGUE ADD CONSTRAINT RefDIPLOMA31 
    FOREIGN KEY (DIPLOMA_ID)
    REFERENCES DIPLOMA(DIPLOMA_ID)
;


-- 
-- TABLE: ACTIVITY_EVALUATION 
--

ALTER TABLE ACTIVITY_EVALUATION ADD CONSTRAINT RefPARTICIPANT26 
    FOREIGN KEY (PARTICIPANT_ID)
    REFERENCES PARTICIPANT(PARTICIPANT_ID)
;


-- 
-- TABLE: DEPARTMENT 
--

ALTER TABLE DEPARTMENT ADD CONSTRAINT RefADMINISTRATOR25 
    FOREIGN KEY (ADMINISTRATOR_ID)
    REFERENCES ADMINISTRATOR(ADMINISTRATOR_ID)
;


-- 
-- TABLE: INSTRUCTOR 
--

ALTER TABLE INSTRUCTOR ADD CONSTRAINT RefPROFESSOR17 
    FOREIGN KEY (PROFESSOR_ID)
    REFERENCES PROFESSOR(PROFESSOR_ID)
;

ALTER TABLE INSTRUCTOR ADD CONSTRAINT RefACTIVITY19 
    FOREIGN KEY (ACTIVITY_ID)
    REFERENCES ACTIVITY(ACTIVITY_ID)
;


-- 
-- TABLE: INSTRUCTOR_EVALUATION 
--

ALTER TABLE INSTRUCTOR_EVALUATION ADD CONSTRAINT RefINSTRUCTOR28 
    FOREIGN KEY (INSTRUCTOR_ID)
    REFERENCES INSTRUCTOR(INSTRUCTOR_ID)
;

ALTER TABLE INSTRUCTOR_EVALUATION ADD CONSTRAINT RefPARTICIPANT29 
    FOREIGN KEY (PARTICIPANT_ID)
    REFERENCES PARTICIPANT(PARTICIPANT_ID)
;


-- 
-- TABLE: PARTICIPANT 
--

ALTER TABLE PARTICIPANT ADD CONSTRAINT RefPROFESSOR16 
    FOREIGN KEY (PROFESSOR_ID)
    REFERENCES PROFESSOR(PROFESSOR_ID)
;

ALTER TABLE PARTICIPANT ADD CONSTRAINT RefACTIVITY20 
    FOREIGN KEY (ACTIVITY_ID)
    REFERENCES ACTIVITY(ACTIVITY_ID)
;


-- 
-- TABLE: PROFESSOR_CAREER 
--

ALTER TABLE PROFESSOR_CAREER ADD CONSTRAINT RefCAREER11 
    FOREIGN KEY (CAREER_ID)
    REFERENCES CAREER(CAREER_ID)
;

ALTER TABLE PROFESSOR_CAREER ADD CONSTRAINT RefPROFESSOR12 
    FOREIGN KEY (PROFESSOR_ID)
    REFERENCES PROFESSOR(PROFESSOR_ID)
;


-- 
-- TABLE: PROFESSOR_CATEGORY 
--

ALTER TABLE PROFESSOR_CATEGORY ADD CONSTRAINT RefCATEGORY1 
    FOREIGN KEY (CATEGORY_ID)
    REFERENCES CATEGORY(CATEGORY_ID)
;

ALTER TABLE PROFESSOR_CATEGORY ADD CONSTRAINT RefPROFESSOR2 
    FOREIGN KEY (PROFESSOR_ID)
    REFERENCES PROFESSOR(PROFESSOR_ID)
;


-- 
-- TABLE: PROFESSOR_DIVISION 
--

ALTER TABLE PROFESSOR_DIVISION ADD CONSTRAINT RefDIVISION7 
    FOREIGN KEY (DIVISION_ID)
    REFERENCES DIVISION(DIVISION_ID)
;

ALTER TABLE PROFESSOR_DIVISION ADD CONSTRAINT RefPROFESSOR9 
    FOREIGN KEY (PROFESSOR_ID)
    REFERENCES PROFESSOR(PROFESSOR_ID)
;


-- 
-- TABLE: PROFESSOR_FACULTY 
--

ALTER TABLE PROFESSOR_FACULTY ADD CONSTRAINT RefPROFESSOR44 
    FOREIGN KEY (PROFESSOR_ID)
    REFERENCES PROFESSOR(PROFESSOR_ID)
;

ALTER TABLE PROFESSOR_FACULTY ADD CONSTRAINT RefFACULTY45 
    FOREIGN KEY (FACULTY_ID)
    REFERENCES FACULTY(FACULTY_ID)
;


-- 
-- TABLE: SEMINAR_TOPIC 
--

ALTER TABLE SEMINAR_TOPIC ADD CONSTRAINT RefINSTRUCTOR38 
    FOREIGN KEY (INSTRUCTOR_ID)
    REFERENCES INSTRUCTOR(INSTRUCTOR_ID)
;

ALTER TABLE SEMINAR_TOPIC ADD CONSTRAINT RefACTIVITY39 
    FOREIGN KEY (ACTIVITY_ID)
    REFERENCES ACTIVITY(ACTIVITY_ID)
;


-- 
-- TABLE: USER 
--

ALTER TABLE USER ADD CONSTRAINT RefDEPARTMENT40 
    FOREIGN KEY (DEPARTMENT_ID)
    REFERENCES DEPARTMENT(DEPARTMENT_ID)
;


