--
-- ER/Studio 8.0 SQL Code Generation
-- Company :      UNAM
-- Project :      magesticd
-- Author :       C. Mauricio Ramos V.,
--                Carolina Kennedy V.
--
-- Date Created : Monday, May 23, 2022 16:10:58
-- Target DBMS : Postgres 14
--
-- Description : Tables definition and structure (DDL)
-- 

\qecho ================== DROPPING OLD TABLES ==================

DROP TABLE ACTIVITY CASCADE
;
DROP TABLE ACTIVITY_CATALOGUE CASCADE
;
DROP TABLE ACTIVITY_EVALUATION CASCADE
;
DROP TABLE ADMINISTRATOR CASCADE
;
DROP TABLE CAREER CASCADE
;
DROP TABLE CATEGORY CASCADE
;
DROP TABLE DEPARTMENT CASCADE
;
DROP TABLE DIPLOMA CASCADE
;
DROP TABLE DIVISION CASCADE
;
DROP TABLE FACULTY CASCADE
;
DROP TABLE INSTRUCTOR CASCADE
;
DROP TABLE INSTRUCTOR_EVALUATION CASCADE
;
DROP TABLE PARTICIPANT CASCADE
;
DROP TABLE PROFESSOR CASCADE
;
DROP TABLE PROFESSOR_CAREER CASCADE
;
DROP TABLE PROFESSOR_CATEGORY CASCADE
;
DROP TABLE PROFESSOR_DIVISION CASCADE
;
DROP TABLE PROFESSOR_FACULTY CASCADE
;
DROP TABLE SEMINAR_TOPIC CASCADE
;
DROP TABLE ACCOUNT CASCADE
;
DROP TABLE VENUE CASCADE
;

\qecho ================== CREATING TABLES ==================

-- 
-- TABLE: ACTIVITY 
--

CREATE TABLE ACTIVITY(
    ACTIVITY_ID              NUMERIC(40, 0)   NOT NULL,
    SEM_YEAR                 INTEGER          NOT NULL,
    SEM_NUM                  INTEGER          NOT NULL,
    SEM_TYPE                 CHAR(1)          NOT NULL,
    START_DATE               DATE             NOT NULL,
    END_DATE                 DATE             NOT NULL,
    MANUAL_DATE              VARCHAR(200)     NOT NULL,
    DAY                      VARCHAR(12)      NOT NULL,
    CTC                      INTEGER,
    COST                     NUMERIC(10, 2)   NOT NULL,
    MAX_QUOTA                INTEGER          NOT NULL,
    MIN_QUOTA                INTEGER          NOT NULL,
    VENUE_ID                 NUMERIC(40, 0)   NOT NULL,
    ACTIVITY_CATALOGUE_ID    NUMERIC(40, 0)   NOT NULL,
    CONSTRAINT ACTIVITY_PK PRIMARY KEY (ACTIVITY_ID),
    CONSTRAINT ACTIVITY_SEM_NUM_CHK CHECK ( SEM_NUM = 1 OR SEM_NUM = 2),
    CONSTRAINT ACTIVITY_SEM_TYPE_CHK CHECK ( SEM_TYPE = 'i' OR SEM_TYPE = 's'),
    CONSTRAINT ACTIVITY_DAY_CHK CHECK (DAY SIMILAR TO '^\[(L,)?(M,)?(I,)?(J,)?(V,)?(S,)?(D,)?\]$'),
    CONSTRAINT ACTIVITY_MAX_QUOTA_CHK CHECK (MAX_QUOTA > 0),
    CONSTRAINT ACTIVITY_MIN_QUOTA_CHK CHECK (MIN_QUOTA > 0)
)
;



-- 
-- TABLE: ACTIVITY_CATALOGUE 
--

CREATE TABLE ACTIVITY_CATALOGUE(
    ACTIVITY_CATALOGUE_ID    NUMERIC(40, 0)    NOT NULL,
    KEY                      VARCHAR(30)      NOT NULL,
    NAME                     VARCHAR(300)     NOT NULL,
    HOURS                    INTEGER          NOT NULL,
    TYPE                     CHAR(2)          NOT NULL,
    INSTITUTION              VARCHAR(10),
    AIMED_AT                 VARCHAR(500),
    OBJECTIVE                VARCHAR(500),
    CONTENT                  VARCHAR(2000),
    BACKGROUND               VARCHAR(500),
    CREATION_DATE            DATE             NOT NULL,
    MODULE                   INTEGER,
    DEPARTMENT_ID            NUMERIC(10, 0)     NOT NULL,
    DIPLOMA_ID               NUMERIC(40, 0),
    CONSTRAINT ACTIVITY_CATALOGUE_PK PRIMARY KEY (ACTIVITY_CATALOGUE_ID),
    CONSTRAINT ACTIVITY_CATALOGUE_TYPE_CHK CHECK (TYPE IN ('CU','CT','TA','SE','FO','EV','DI','CO')),
    CONSTRAINT ACTIVITY_CATALOGUE_INSTITUTION_CHK CHECK (INSTITUTION = 'DGAPA' OR INSTITUTION = 'CDD')
)
;



-- 
-- TABLE: ACTIVITY_EVALUATION 
--

CREATE TABLE ACTIVITY_EVALUATION(
    ACTIVITY_EVALUATION_ID    NUMERIC(40, 0)    NOT NULL,
    QUESTION_1_1              INTEGER,
    QUESTION_1_2              INTEGER,
    QUESTION_1_3              INTEGER,
    QUESTION_1_4              INTEGER,
    QUESTION_1_5              INTEGER,
    QUESTION_2_1              INTEGER,
    QUESTION_2_2              INTEGER,
    QUESTION_2_3              INTEGER,
    QUESTION_2_4              INTEGER,
    QUESTION_3_1              INTEGER,
    QUESTION_3_2              INTEGER,
    QUESTION_3_3              INTEGER,
    QUESTION_3_4              INTEGER,
    QUESTION_4                BOOLEAN,
    QUESTION_5                VARCHAR(20),
    QUESTION_6                VARCHAR(500),
    QUESTION_7                VARCHAR(500),
    QUESTION_8                VARCHAR(400),
    QUESTION_9                VARCHAR(20),
    QUESTION_10               VARCHAR(300),
    SEM_SCHEDULE              VARCHAR(500),
    INT_SCHEDULE              VARCHAR(500),
    PARTICIPANT_ID            NUMERIC(40, 0)    NOT NULL,
    CONSTRAINT ACTIVITY_EVALUATION_PK PRIMARY KEY (ACTIVITY_EVALUATION_ID),
    CONSTRAINT AE_QUESTION_1_2_CHK CHECK (QUESTION_1_2 IN (0,50,60,80,95,100)),
    CONSTRAINT AE_QUESTION_1_3_CHK CHECK (QUESTION_1_3 IN (0,50,60,80,95,100)),
    CONSTRAINT AE_QUESTION_1_4_CHK CHECK (QUESTION_1_4 IN (0,50,60,80,95,100)),
    CONSTRAINT AE_QUESTION_1_1_CHK CHECK (QUESTION_1_1 IN (0,50,60,80,95,100)),
    CONSTRAINT AE_QUESTION_1_5_CHK CHECK (QUESTION_1_5 IN (0,50,60,80,95,100)),
    CONSTRAINT AE_QUESTION_2_1_CHK CHECK (QUESTION_2_1 IN (0,50,60,80,95,100)),
    CONSTRAINT AE_QUESTION_2_2_CHK CHECK (QUESTION_2_2 IN (0,50,60,80,95,100)),
    CONSTRAINT AE_QUESTION_2_3_CHK CHECK (QUESTION_2_3 IN (0,50,60,80,95,100)),
    CONSTRAINT AE_QUESTION_2_4_CHK CHECK (QUESTION_2_4 IN (0,50,60,80,95,100)),
    CONSTRAINT AE_QUESTION_3_1_CHK CHECK (QUESTION_3_1 IN (0,50,60,80,95,100)),
    CONSTRAINT AE_QUESTION_3_2_CHK CHECK (QUESTION_3_2 IN (0,50,60,80,95,100)),
    CONSTRAINT AE_QUESTION_3_3_CHK CHECK (QUESTION_3_3 IN (0,50,60,80,95,100)),
    CONSTRAINT AE_QUESTION_3_4_CHK CHECK (QUESTION_3_4 IN (0,50,60,80,95,100)),
    CONSTRAINT AE_QUESTION_5_CHK CHECK (QUESTION_5 SIMILAR TO '^\[(I,)?(F,)?(J,)?(O,)?\]$'),
    CONSTRAINT AE_QUESTION_9_CHK CHECK (QUESTION_9 SIMILAR TO '^\[(P,)?(H,)?(C,)?(I,)?(O,)?\]$')
)
;



-- 
-- TABLE: ADMINISTRATOR 
--

CREATE TABLE ADMINISTRATOR(
    ADMINISTRATOR_ID     NUMERIC(10, 0)  NOT NULL,
    NAME                 VARCHAR(100)    NOT NULL,
    LAST_NAME            VARCHAR(40)     NOT NULL,
    MOTHERS_LAST_NAME    VARCHAR(40),
    DEGREE               VARCHAR(40),
    GENDER               CHAR(1),
    JOB                  CHAR(1)         NOT NULL,
    CONSTRAINT ADMINISTRATOR_PK PRIMARY KEY (ADMINISTRATOR_ID),
    CONSTRAINT ADMINISTRATOR_GENDER_CHK CHECK (GENDER = 'M' OR GENDER = 'F'),
    CONSTRAINT ADMINISTRATOR_JOB_CHK CHECK (JOB IN ('C', 'O', 'S', 'D'))
)
;



-- 
-- TABLE: CAREER 
--

CREATE TABLE CAREER(
    CAREER_ID    NUMERIC(10, 0)  NOT NULL,
    NAME         VARCHAR(100)    NOT NULL,
    KEY          VARCHAR(30)     NOT NULL,
    CONSTRAINT CAREER_PK PRIMARY KEY (CAREER_ID),
    CONSTRAINT CAREER_KEY_UK UNIQUE (KEY)
)
;



-- 
-- TABLE: CATEGORY 
--

CREATE TABLE CATEGORY(
    CATEGORY_ID     NUMERIC(10, 0)  NOT NULL,
    NAME            VARCHAR(50)     NOT NULL,
    ABBREVIATION    VARCHAR(20)     NOT NULL,
    CONSTRAINT CATEGORY_PK PRIMARY KEY (CATEGORY_ID)
)
;



-- 
-- TABLE: DEPARTMENT 
--

CREATE TABLE DEPARTMENT(
    DEPARTMENT_ID       NUMERIC(10, 0)  NOT NULL,
    ABBREVIATION        VARCHAR(40)     NOT NULL,
    NAME                VARCHAR(100)    NOT NULL,
    ADMINISTRATOR_ID    NUMERIC(10, 0)  NOT NULL,
    CONSTRAINT DEPARTMENT_PK PRIMARY KEY (DEPARTMENT_ID)
)
;



-- 
-- TABLE: DIPLOMA 
--

CREATE TABLE DIPLOMA(
    DIPLOMA_ID    NUMERIC(40, 0)  NOT NULL,
    NAME          VARCHAR(300)    NOT NULL,
    CONSTRAINT DIPLOMA_PK PRIMARY KEY (DIPLOMA_ID)
)
;



-- 
-- TABLE: DIVISION 
--

CREATE TABLE DIVISION(
    DIVISION_ID     NUMERIC(10, 0)  NOT NULL,
    NAME            VARCHAR(60)     NOT NULL,
    ABBREVIATION    VARCHAR(30)     NOT NULL,
    CONSTRAINT DIVISION_PK PRIMARY KEY (DIVISION_ID)
)
;



-- 
-- TABLE: FACULTY 
--

CREATE TABLE FACULTY(
    FACULTY_ID    NUMERIC(10, 0)   NOT NULL,
    NAME          VARCHAR(60)     NOT NULL,
    CONSTRAINT FACULTY_PK PRIMARY KEY (FACULTY_ID)
)
;



-- 
-- TABLE: INSTRUCTOR 
--

CREATE TABLE INSTRUCTOR(
    INSTRUCTOR_ID    NUMERIC(40, 0)    NOT NULL,
    KEY              VARCHAR(10),
    SEND_DATE        DATE,
    PROFESSOR_ID     NUMERIC(40, 0)    NOT NULL,
    ACTIVITY_ID      NUMERIC(40, 0)    NOT NULL,
    CONSTRAINT INSTRUCTOR_PK PRIMARY KEY (INSTRUCTOR_ID),
    CONSTRAINT INSTRUCTOR_KEY_CHK CHECK (KEY SIMILAR TO '^F04[0-9]{4}[CTSDEF][0-9]{3}R[0-9]{4}$'),
    CONSTRAINT INSTRUCTOR_KEY_UK UNIQUE (KEY)
)
;



-- 
-- TABLE: INSTRUCTOR_EVALUATION 
--

CREATE TABLE INSTRUCTOR_EVALUATION(
    INSTRUCTOR_EVALUATION_ID    NUMERIC(40, 0)    NOT NULL,
    QUESTION_1                  INTEGER,
    QUESTION_2                  INTEGER,
    QUESTION_3                  INTEGER,
    QUESTION_4                  INTEGER,
    QUESTION_5                  INTEGER,
    QUESTION_6                  INTEGER,
    QUESTION_7                  INTEGER,
    QUESTION_8                  INTEGER,
    QUESTION_9                  INTEGER,
    QUESTION_10                 INTEGER,
    QUESTION_11                 INTEGER,
    INSTRUCTOR_ID               NUMERIC(40, 0)    NOT NULL,
    PARTICIPANT_ID              NUMERIC(40, 0)    NOT NULL,
    CONSTRAINT INSTRUCTOR_EVALUATION_PK PRIMARY KEY (INSTRUCTOR_EVALUATION_ID),
    CONSTRAINT IE_QUESTION_1_CHK  CHECK (QUESTION_1 IN (0,50,60,80,95,100)),
    CONSTRAINT IE_QUESTION_2_CHK  CHECK (QUESTION_2 IN (0,50,60,80,95,100)),
    CONSTRAINT IE_QUESTION_3_CHK  CHECK (QUESTION_3 IN (0,50,60,80,95,100)),
    CONSTRAINT IE_QUESTION_4_CHK  CHECK (QUESTION_4 IN (0,50,60,80,95,100)),
    CONSTRAINT IE_QUESTION_5_CHK  CHECK (QUESTION_5 IN (0,50,60,80,95,100)),
    CONSTRAINT IE_QUESTION_6_CHK  CHECK (QUESTION_6 IN (0,50,60,80,95,100)),
    CONSTRAINT IE_QUESTION_7_CHK  CHECK (QUESTION_7 IN (0,50,60,80,95,100)),
    CONSTRAINT IE_QUESTION_8_CHK  CHECK (QUESTION_8 IN (0,50,60,80,95,100)),
    CONSTRAINT IE_QUESTION_9_CHK  CHECK (QUESTION_9 IN (0,50,60,80,95,100)),
    CONSTRAINT IE_QUESTION_10_CHK CHECK (QUESTION_10 IN (0,50,60,80,95,100)),
    CONSTRAINT IE_QUESTION_11_CHK CHECK (QUESTION_11 IN (0,50,60,80,95,100))
)
;



-- 
-- TABLE: PARTICIPANT 
--

CREATE TABLE PARTICIPANT(
    PARTICIPANT_ID    NUMERIC(40, 0)   NOT NULL,
    ADDITIONAL        BOOLEAN         NOT NULL,
    ATTENDANCE        BOOLEAN         NOT NULL,
    ACCREDITED        BOOLEAN         NOT NULL,
    CONFIRMATION      BOOLEAN         NOT NULL,
    CANCELED          BOOLEAN         NOT NULL,
    FREE              BOOLEAN         NOT NULL,
    DISCOUNT          NUMERIC(4, 4)    NOT NULL,
    DEPOSIT           NUMERIC(10, 2)   NOT NULL,
    WL_WAS            BOOLEAN         NOT NULL,
    WL_NUMBER         INTEGER,
    NAC               VARCHAR(300),
    GRADE             INTEGER,
    COMMENT           VARCHAR(300),
    KEY               VARCHAR(20),
    SEND_DATE         DATE,
    PROFESSOR_ID      NUMERIC(40, 0)   NOT NULL,
    ACTIVITY_ID       NUMERIC(40, 0)   NOT NULL,
    CONSTRAINT PARTICIPANT_PK PRIMARY KEY (PARTICIPANT_ID),
    CONSTRAINT PARTICIPANT_DISCOUNT_CHK CHECK ((FREE = TRUE AND DISCOUNT = 0) OR FREE = FALSE),
    CONSTRAINT PARTICIPANT_DEPOSIT_CHK CHECK ((FREE = TRUE AND DEPOSIT = 0) OR FREE = FALSE),
    CONSTRAINT PARTICIPANT_KEY_CHK CHECK (KEY SIMILAR TO '^F04[0-9]{4}[CTSDEF][0-9]{3}C[0-9]{4}$')
)
;



-- 
-- TABLE: PROFESSOR 
--

CREATE TABLE PROFESSOR(
    PROFESSOR_ID         NUMERIC(40, 0)   NOT NULL,
    NAME                 VARCHAR(100)    NOT NULL,
    LAST_NAME            VARCHAR(50)     NOT NULL,
    MOTHERS_LAST_NAME    VARCHAR(50),
    RFC                  VARCHAR(15),
    WORKER_NUMBER       VARCHAR(30),
    BIRTHDATE            DATE,
    PHONE_NUMBER        VARCHAR(15),
    DEGREE               VARCHAR(40),
    EMAIL                VARCHAR(40),
    GENDER               CHAR(1),
    SEMBLANCE            VARCHAR(200),
    FACEBOOK             VARCHAR(40),
    IS_INSTRUCTOR        BOOLEAN         NOT NULL,
    IS_UNAM              BOOLEAN         NOT NULL,
    PROVENANCE           VARCHAR(100),
    CONSTRAINT PROFESSOR_PK PRIMARY KEY (PROFESSOR_ID),
    CONSTRAINT PROFESSOR_RFC_CHK CHECK (LENGTH(RFC) = 13 OR LENGTH(RFC) = 10),
    CONSTRAINT PROFESSOR_GENDER_CHK CHECK (GENDER = 'M' OR GENDER = 'F'),
    CONSTRAINT PROFESSOR_PROVENANCE_CHK CHECK ((IS_UNAM = FALSE AND PROVENANCE IS NOT NULL) OR IS_UNAM = TRUE),
    CONSTRAINT PROFESSOR_RFC_UK UNIQUE (RFC),
    CONSTRAINT PROFESSOR_WORKER_NUMBER_UK UNIQUE (WORKER_NUMBER)
)
;



-- 
-- TABLE: PROFESSOR_CAREER 
--

CREATE TABLE PROFESSOR_CAREER(
    PROFESSOR_CAREER_ID    NUMERIC(40, 0)    NOT NULL,
    CAREER_ID              NUMERIC(10, 0)    NOT NULL,
    PROFESSOR_ID           NUMERIC(40, 0)    NOT NULL,
    CONSTRAINT PROFESSOR_CAREER_PK PRIMARY KEY (PROFESSOR_CAREER_ID)
)
;



-- 
-- TABLE: PROFESSOR_CATEGORY 
--

CREATE TABLE PROFESSOR_CATEGORY(
    PROFESSOR_CATEGORY_ID    NUMERIC(40, 0)    NOT NULL,
    NUMERIC                   INTEGER          NOT NULL,
    PROFESSOR_ID             NUMERIC(40, 0)    NOT NULL,
    CATEGORY_ID              NUMERIC(10, 0)    NOT NULL,
    CONSTRAINT PROFESSOR_CATEGORY_PK PRIMARY KEY (PROFESSOR_CATEGORY_ID)
)
;



-- 
-- TABLE: PROFESSOR_DIVISION 
--

CREATE TABLE PROFESSOR_DIVISION(
    PROFESSOR_DIVISION_ID    NUMERIC(40, 0)    NOT NULL,
    DIVISION_ID              NUMERIC(10, 0)    NOT NULL,
    PROFESSOR_ID             NUMERIC(40, 0)    NOT NULL,
    CONSTRAINT PROFESSOR_DIVISION_PK PRIMARY KEY (PROFESSOR_DIVISION_ID)
)
;



-- 
-- TABLE: PROFESSOR_FACULTY 
--

CREATE TABLE PROFESSOR_FACULTY(
    PROFESSOR_FACULTY_ID    VARCHAR(40)     NOT NULL,
    PROFESSOR_ID            NUMERIC(40, 0)    NOT NULL,
    FACULTY_ID              NUMERIC(10, 0)    NOT NULL,
    CONSTRAINT PROFESSOR_FACULTY_PK PRIMARY KEY (PROFESSOR_FACULTY_ID)

)
;



-- 
-- TABLE: SEMINAR_TOPIC 
--

CREATE TABLE SEMINAR_TOPIC(
    SEMINAR_TOPIC_ID    VARCHAR(40)     NOT NULL,
    NAME                VARCHAR(300)    NOT NULL,
    HOURS               INTEGER         NOT NULL,
    EX_DATE             DATE            NOT NULL,
    INSTRUCTOR_ID       NUMERIC(40, 0)   NOT NULL,
    ACTIVITY_ID         NUMERIC(40, 0)   NOT NULL,
    CONSTRAINT SEMINAR_TOPIC_PK PRIMARY KEY (SEMINAR_TOPIC_ID)
)
;



-- 
-- TABLE: ACCOUNT 
--

CREATE TABLE ACCOUNT(
    ACCOUNT_ID       NUMERIC(40, 0)   NOT NULL,
    NAME             VARCHAR(60)     NOT NULL,
    USERNAME         VARCHAR(40)     NOT NULL,
    PASSWORD         VARCHAR(60)     NOT NULL,
    ADMIN            BOOLEAN         NOT NULL,
    DEPARTMENT_ID    NUMERIC(10, 0),
    CONSTRAINT ACCOUNT_PK PRIMARY KEY (ACCOUNT_ID),
    CONSTRAINT ACCOUNT_USERNAME_UK UNIQUE (USERNAME)
)
;



-- 
-- TABLE: VENUE 
--

CREATE TABLE VENUE(
    VENUE_ID    NUMERIC(40, 0)   NOT NULL,
    NAME        VARCHAR(100)    NOT NULL,
    CAPACITY    INTEGER         NOT NULL,
    LOCATION    VARCHAR(200)    NOT NULL,
    CONSTRAINT VENUE_PK PRIMARY KEY (VENUE_ID),
    CONSTRAINT VENUE_CAPACITY_CHK CHECK (CAPACITY > 0)
)
;

\qecho ================== ADDING FOREIGN KEYS ==================

-- 
-- TABLE: ACTIVITY 
--

ALTER TABLE ACTIVITY ADD CONSTRAINT ACTIVITY_VENUE_ID_FK
    FOREIGN KEY (VENUE_ID)
    REFERENCES VENUE(VENUE_ID)
;

ALTER TABLE ACTIVITY ADD CONSTRAINT ACTIVITY_ACTIVITY_CATALOGUE_ID_FK
    FOREIGN KEY (ACTIVITY_CATALOGUE_ID)
    REFERENCES ACTIVITY_CATALOGUE(ACTIVITY_CATALOGUE_ID)
;


-- 
-- TABLE: ACTIVITY_CATALOGUE 
--

ALTER TABLE ACTIVITY_CATALOGUE ADD CONSTRAINT ACTIVITY_CATALOGUE_DEPARTMENT_ID_FK
    FOREIGN KEY (DEPARTMENT_ID)
    REFERENCES DEPARTMENT(DEPARTMENT_ID)
;

ALTER TABLE ACTIVITY_CATALOGUE ADD CONSTRAINT ACTIVITY_CATALOGUE_DIPLOMA_ID_FK
    FOREIGN KEY (DIPLOMA_ID)
    REFERENCES DIPLOMA(DIPLOMA_ID)
;


-- 
-- TABLE: ACTIVITY_EVALUATION 
--

ALTER TABLE ACTIVITY_EVALUATION ADD CONSTRAINT ACTIVITY_EVALUATION_PARTICIPANT_ID_FK
    FOREIGN KEY (PARTICIPANT_ID)
    REFERENCES PARTICIPANT(PARTICIPANT_ID)
;


-- 
-- TABLE: DEPARTMENT 
--

ALTER TABLE DEPARTMENT ADD CONSTRAINT DEPARTMENT_ADMINISTRATOR_ID_FK
    FOREIGN KEY (ADMINISTRATOR_ID)
    REFERENCES ADMINISTRATOR(ADMINISTRATOR_ID)
;


-- 
-- TABLE: INSTRUCTOR 
--

ALTER TABLE INSTRUCTOR ADD CONSTRAINT INSTRUCTOR_PROFESSOR_ID_FK
    FOREIGN KEY (PROFESSOR_ID)
    REFERENCES PROFESSOR(PROFESSOR_ID)
;

ALTER TABLE INSTRUCTOR ADD CONSTRAINT INSTRUCTOR_ACTIVITY_ID_FK 
    FOREIGN KEY (ACTIVITY_ID)
    REFERENCES ACTIVITY(ACTIVITY_ID)
;


-- 
-- TABLE: INSTRUCTOR_EVALUATION 
--

ALTER TABLE INSTRUCTOR_EVALUATION ADD CONSTRAINT INSTRUCTOR_EVALUATION_INSTRUCTOR_ID_FK
    FOREIGN KEY (INSTRUCTOR_ID)
    REFERENCES INSTRUCTOR(INSTRUCTOR_ID)
;

ALTER TABLE INSTRUCTOR_EVALUATION ADD CONSTRAINT INSTRUCTOR_EVALUATION_PARTICIPANT_ID_FK
    FOREIGN KEY (PARTICIPANT_ID)
    REFERENCES PARTICIPANT(PARTICIPANT_ID)
;


-- 
-- TABLE: PARTICIPANT 
--

ALTER TABLE PARTICIPANT ADD CONSTRAINT PARTICIPANT_PROFESSOR_ID_FK
    FOREIGN KEY (PROFESSOR_ID)
    REFERENCES PROFESSOR(PROFESSOR_ID)
;

ALTER TABLE PARTICIPANT ADD CONSTRAINT PARTICIPANT_ACTIVITY_ID_FK
    FOREIGN KEY (ACTIVITY_ID)
    REFERENCES ACTIVITY(ACTIVITY_ID)
;


-- 
-- TABLE: PROFESSOR_CAREER 
--

ALTER TABLE PROFESSOR_CAREER ADD CONSTRAINT PROFESSOR_CAREER_CAREER_ID_FK
    FOREIGN KEY (CAREER_ID)
    REFERENCES CAREER(CAREER_ID)
;

ALTER TABLE PROFESSOR_CAREER ADD CONSTRAINT PROFESSOR_CARREER_PROFESSOR_ID_FK
    FOREIGN KEY (PROFESSOR_ID)
    REFERENCES PROFESSOR(PROFESSOR_ID)
;


-- 
-- TABLE: PROFESSOR_CATEGORY 
--

ALTER TABLE PROFESSOR_CATEGORY ADD CONSTRAINT PROFESSOR_CATEGORY_CATEGORY_ID_FK
    FOREIGN KEY (CATEGORY_ID)
    REFERENCES CATEGORY(CATEGORY_ID)
;

ALTER TABLE PROFESSOR_CATEGORY ADD CONSTRAINT PROFESSOR_CATEGORY_PROFESSOR_ID_FK
    FOREIGN KEY (PROFESSOR_ID)
    REFERENCES PROFESSOR(PROFESSOR_ID)
;


-- 
-- TABLE: PROFESSOR_DIVISION 
--

ALTER TABLE PROFESSOR_DIVISION ADD CONSTRAINT PROFESSOR_DIVISION_DIVISION_ID_FK
    FOREIGN KEY (DIVISION_ID)
    REFERENCES DIVISION(DIVISION_ID)
;

ALTER TABLE PROFESSOR_DIVISION ADD CONSTRAINT PROFESSOR_DIVISION_PROFESSOR_ID_FK 
    FOREIGN KEY (PROFESSOR_ID)
    REFERENCES PROFESSOR(PROFESSOR_ID)
;


-- 
-- TABLE: PROFESSOR_FACULTY 
--

ALTER TABLE PROFESSOR_FACULTY ADD CONSTRAINT PROFESSOR_FACULTY_PROFESSOR_ID_FK
    FOREIGN KEY (PROFESSOR_ID)
    REFERENCES PROFESSOR(PROFESSOR_ID)
;

ALTER TABLE PROFESSOR_FACULTY ADD CONSTRAINT PROFESSOR_FACULTY_FACULTY_ID_FK
    FOREIGN KEY (FACULTY_ID)
    REFERENCES FACULTY(FACULTY_ID)
;


-- 
-- TABLE: SEMINAR_TOPIC 
--

ALTER TABLE SEMINAR_TOPIC ADD CONSTRAINT SEMINAR_TOPIC_INSTRUCTOR_ID_FK 
    FOREIGN KEY (INSTRUCTOR_ID)
    REFERENCES INSTRUCTOR(INSTRUCTOR_ID)
;

ALTER TABLE SEMINAR_TOPIC ADD CONSTRAINT SEMINAR_TOPIC_ACTIVITY_ID_FK
    FOREIGN KEY (ACTIVITY_ID)
    REFERENCES ACTIVITY(ACTIVITY_ID)
;


-- 
-- TABLE: ACCOUNT 
--

ALTER TABLE ACCOUNT ADD CONSTRAINT ACCOUNT_DEPARTMENT_ID_FK
    FOREIGN KEY (DEPARTMENT_ID)
    REFERENCES DEPARTMENT(DEPARTMENT_ID)
;