--
-- Company :      UNAM
-- Project :      MagestiCD
-- Author :       C. Mauricio Ramos V.,
--                Carolina Kennedy V.
--
-- Date Created : Monday, May 23, 2022 16:10:58
-- Target DBMS : Oracle 11g
--
-- Description : Sequencies creation (DDL) for the ID's
--

PROMPT ================== DROPPING OLD SEQUENCIES ==================

DROP SEQUENCE ACTIVITY_SEQ
;
DROP SEQUENCE ACTIVITY_CATALOGUE_SEQ
;
DROP SEQUENCE ACTIVITY_EVALUATION_SEQ
;
DROP SEQUENCE ADMINISTRATOR_SEQ
;
DROP SEQUENCE CAREER_SEQ
;
DROP SEQUENCE CATEGORY_SEQ
;
DROP SEQUENCE DEPARTMENT_SEQ
;
DROP SEQUENCE DIPLOMA_SEQ
;
DROP SEQUENCE DIVISION_SEQ
;
DROP SEQUENCE FACULTY_SEQ
;
DROP SEQUENCE INSTRUCTOR_SEQ
;
DROP SEQUENCE INSTRUCTOR_EVALUATION_SEQ
;
DROP SEQUENCE PARTICIPANT_SEQ
;
DROP SEQUENCE PROFESSOR_SEQ
;
DROP SEQUENCE PROFESSOR_CAREER_SEQ
;
DROP SEQUENCE PROFESSOR_CATEGORY_SEQ
;
DROP SEQUENCE PROFESSOR_DIVISION_SEQ
;
DROP SEQUENCE PROFESSOR_FACULTY_SEQ
;
DROP SEQUENCE SEMINAR_TOPIC_SEQ
;
DROP SEQUENCE USER_SEQ
;
DROP SEQUENCE VENUE_SEQ
;



PROMPT ================== CREATING SEQUENCIES ==================

CREATE SEQUENCE ACTIVITY_SEQ
    START WITH 1
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
    NOCYCLE
    CACHE 20
    ORDER
;

CREATE SEQUENCE ACTIVITY_CATALOGUE_SEQ
    START WITH 1
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
    NOCYCLE
    CACHE 20
    ORDER
;

CREATE SEQUENCE ACTIVITY_EVALUATION_SEQ
    START WITH 1
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
    NOCYCLE
    CACHE 20
    ORDER
;

CREATE SEQUENCE ADMINISTRATOR_SEQ
    START WITH 1
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
    NOCYCLE
    CACHE 20
    ORDER
;

CREATE SEQUENCE CAREER_SEQ
    START WITH 1
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
    NOCYCLE
    CACHE 20
    ORDER
;

CREATE SEQUENCE CATEGORY_SEQ
    START WITH 1
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
    NOCYCLE
    CACHE 20
    ORDER
;

CREATE SEQUENCE DEPARTMENT_SEQ
    START WITH 1
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
    NOCYCLE
    CACHE 20
    ORDER
;

CREATE SEQUENCE DIPLOMA_SEQ
    START WITH 1
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
    NOCYCLE
    CACHE 20
    ORDER
;

CREATE SEQUENCE DIVISION_SEQ
    START WITH 1
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
    NOCYCLE
    CACHE 20
    ORDER
;

CREATE SEQUENCE FACULTY_SEQ
    START WITH 1
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
    NOCYCLE
    CACHE 20
    ORDER
;

CREATE SEQUENCE INSTRUCTOR_SEQ
    START WITH 1
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
    NOCYCLE
    CACHE 20
    ORDER
;

CREATE SEQUENCE INSTRUCTOR_EVALUATION_SEQ
    START WITH 1
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
    NOCYCLE
    CACHE 20
    ORDER
;

CREATE SEQUENCE PARTICIPANT_SEQ
    START WITH 1
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
    NOCYCLE
    CACHE 20
    ORDER
;

CREATE SEQUENCE PROFESSOR_SEQ
    START WITH 1
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
    NOCYCLE
    CACHE 20
    ORDER
;

CREATE SEQUENCE PROFESSOR_CAREER_SEQ
    START WITH 1
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
    NOCYCLE
    CACHE 20
    ORDER
;

CREATE SEQUENCE PROFESSOR_CATEGORY_SEQ
    START WITH 1
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
    NOCYCLE
    CACHE 20
    ORDER
;

CREATE SEQUENCE PROFESSOR_DIVISION_SEQ
    START WITH 1
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
    NOCYCLE
    CACHE 20
    ORDER
;

CREATE SEQUENCE PROFESSOR_FACULTY_SEQ
    START WITH 1
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
    NOCYCLE
    CACHE 20
    ORDER
;

CREATE SEQUENCE SEMINAR_TOPIC_SEQ
    START WITH 1
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
    NOCYCLE
    CACHE 20
    ORDER
;

CREATE SEQUENCE USER_SEQ
    START WITH 1
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
    NOCYCLE
    CACHE 20
    ORDER
;

CREATE SEQUENCE VENUE_SEQ
    START WITH 1
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
    NOCYCLE
    CACHE 20
    ORDER
;