--
-- ER/Studio 8.0 SQL Code Generation
-- Company :      UNAM
-- Project :      magesticd
-- Author :       C. Mauricio Ramos V.,
--                Carolina Kennedy V.
--
-- Date Created : Monday, May 23, 2022 16:10:58
-- Target DBMS : Postgres 14
--
-- Description : Tables definition and structure (DDL)
-- 

\qecho ================== DROPPING OLD TABLES ==================

DROP TABLE ACTIVITY CASCADE CONSTRAINTS
;
DROP TABLE ACTIVITY_CATALOGUE CASCADE CONSTRAINTS
;
DROP TABLE ACTIVITY_EVALUATION CASCADE CONSTRAINTS
;
DROP TABLE ADMINISTRATOR CASCADE CONSTRAINTS
;
DROP TABLE CAREER CASCADE CONSTRAINTS
;
DROP TABLE CATEGORY CASCADE CONSTRAINTS
;
DROP TABLE DEPARTMENT CASCADE CONSTRAINTS
;
DROP TABLE DIPLOMA CASCADE CONSTRAINTS
;
DROP TABLE DIVISION CASCADE CONSTRAINTS
;
DROP TABLE FACULTY CASCADE CONSTRAINTS
;
DROP TABLE INSTRUCTOR CASCADE CONSTRAINTS
;
DROP TABLE INSTRUCTOR_EVALUATION CASCADE CONSTRAINTS
;
DROP TABLE PARTICIPANT CASCADE CONSTRAINTS
;
DROP TABLE PROFESSOR CASCADE CONSTRAINTS
;
DROP TABLE PROFESSOR_CAREER CASCADE CONSTRAINTS
;
DROP TABLE PROFESSOR_CATEGORY CASCADE CONSTRAINTS
;
DROP TABLE PROFESSOR_DIVISION CASCADE CONSTRAINTS
;
DROP TABLE PROFESSOR_FACULTY CASCADE CONSTRAINTS
;
DROP TABLE SEMINAR_TOPIC CASCADE CONSTRAINTS
;
DROP TABLE USER CASCADE CONSTRAINTS
;
DROP TABLE VENUE CASCADE CONSTRAINTS
;

\qecho ================== CREATING TABLES ==================

-- 
-- TABLE: ACTIVITY 
--

CREATE TABLE ACTIVITY(
    ACTIVITY_ID              NUMERIC(40, 0)   NOT NULL DEFAULT ACTIVITY_SEQ.NEXTVAL,
    SEM_YEAR                 INTEGER          NOT NULL,
    SEM_NUM                  INTEGER          NOT NULL,
    SEM_TYPE                 CHAR(1)          NOT NULL,
    START_DATE               DATE             NOT NULL,
    END_DATE                 DATE             NOT NULL,
    MANUAL_DATE              VARCHAR(200)     NOT NULL,
    DAY                      VARCHAR(12)      NOT NULL,
    CTC                      INTEGER,
    COST                     NUMERIC(10, 2)   NOT NULL,
    MAX_QUOTA                INTEGER          NOT NULL,
    MIN_QUOTA                INTEGER          NOT NULL,
    VENUE_ID                 NUMERIC(20, 0)   NOT NULL,
    ACTIVITY_CATALOGUE_ID    NUMERIC(40, 0)   NOT NULL,
    CONSTRAINT ACTIVITY_PK PRIMARY KEY (ACTIVITY_ID),
    CONSTRAINT ACTIVITY_SEM_NUM_CHK CHECK ( SEM_NUM = 1 OR SEM_NUM = 2),
    CONSTRAINT ACTIVITY_SEM_TYPE_CHK CHECK ( SEM_TYPE = 'i' OR SEM_TYPE = 's'),
    CONSTRAINT ACTIVITY_DAY_CHK CHECK (DAY SIMILAR TO '^\[(L,)?(M,)?(I,)?(J,)?(V,)?(S,)?(D,)?\]$'),
    CONSTRAINT ACTIVITY_MAX_QUOTA_CHK CHECK (MAX_QUOTA > 0),
    CONSTRAINT ACTIVITY_MIN_QUOTA_CHK CHECK (MIN_QUOTA > 0)
)
;



-- 
-- TABLE: ACTIVITY_CATALOGUE 
--

CREATE TABLE ACTIVITY_CATALOGUE(
    ACTIVITY_CATALOGUE_ID    NUMERIC(40, 0)     NOT NULL DEFAULT ACTIVITY_CATALOGUE_SEQ.NEXTVAL,
    KEY                      VARCHAR(30)      NOT NULL,
    NAME                     VARCHAR(300)     NOT NULL,
    HOURS                    INTEGER      NOT NULL,
    TYPE                     VARCHAR(2)       NOT NULL,
    INSTITUTION              VARCHAR(10),
    AIMED_AT                 VARCHAR(500),
    OBJECTIVE                VARCHAR(500),
    CONTENT                  VARCHAR(2000),
    BACKGROUND               VARCHAR(500),
    CREATION_DATE            DATE              NOT NULL,
    MODULE                   NUMERIC(10, 0),
    DEPARTMENT_ID            NUMERIC(10, 0)     NOT NULL,
    DIPLOMA_ID               NUMERIC(20, 0),
    CONSTRAINT ACTIVITY_CATALOGUE_PK PRIMARY KEY (ACTIVITY_CATALOGUE_ID),
    CONSTRAINT ACTIVITY_CATALOGUE_TYPE_CHK CHECK (TYPE IN ('CU','CT','TA','SE','FO','EV','DI','CO')),
    CONSTRAINT ACTIVITY_CATALOGUE_INSTITUTION_CHK CHECK (INSTITUTION = 'DGAPA' OR INSTITUTION = 'CDD')
)
;



-- 
-- TABLE: ACTIVITY_EVALUATION 
--

CREATE TABLE ACTIVITY_EVALUATION(
    ACTIVITY_EVALUATION_ID    NUMERIC(40, 0)    NOT NULL DEFAULT ACTIVITY_EVALUATION_SEQ.NEXTVAL,
    QUESTION_1_1              NUMERIC(2, 0),
    QUESTION_1_2              NUMERIC(2, 0),
    QUESTION_1_3              NUMERIC(2, 0),
    QUESTION_1_4              NUMERIC(2, 0),
    QUESTION_1_5              NUMERIC(2, 0),
    QUESTION_2_1              NUMERIC(2, 0),
    QUESTION_2_2              NUMERIC(2, 0),
    QUESTION_2_3              NUMERIC(2, 0),
    QUESTION_2_4              NUMERIC(2, 0),
    QUESTION_3_1              NUMERIC(2, 0),
    QUESTION_3_2              NUMERIC(2, 0),
    QUESTION_3_3              NUMERIC(2, 0),
    QUESTION_3_4              NUMERIC(2, 0),
    QUESTION_4                NUMERIC(1, 0),
    QUESTION_5                VARCHAR(20),
    QUESTION_6                VARCHAR(500),
    QUESTION_7                VARCHAR(500),
    QUESTION_8                VARCHAR(400),
    QUESTION_9                VARCHAR(20),
    QUESTION_10               VARCHAR(300),
    SEM_SCHEDULE              VARCHAR(500),
    INT_SCHEDULE              VARCHAR(500),
    PARTICIPANT_ID            NUMERIC(40, 0)    NOT NULL,
    CONSTRAINT ACTIVITY_EVALUATION_PK PRIMARY KEY (ACTIVITY_EVALUATION_ID),
    CONSTRAINT AE_QUESTION_1_2_CHK CHECK (QUESTION_1_2 IN (0,50,60,80,95,100)),
    CONSTRAINT AE_QUESTION_1_3_CHK CHECK (QUESTION_1_3 IN (0,50,60,80,95,100)),
    CONSTRAINT AE_QUESTION_1_4_CHK CHECK (QUESTION_1_4 IN (0,50,60,80,95,100)),
    CONSTRAINT AE_QUESTION_1_1_CHK CHECK (QUESTION_1_1 IN (0,50,60,80,95,100)),
    CONSTRAINT AE_QUESTION_1_5_CHK CHECK (QUESTION_1_5 IN (0,50,60,80,95,100)),
    CONSTRAINT AE_QUESTION_2_1_CHK CHECK (QUESTION_2_1 IN (0,50,60,80,95,100)),
    CONSTRAINT AE_QUESTION_2_2_CHK CHECK (QUESTION_2_2 IN (0,50,60,80,95,100)),
    CONSTRAINT AE_QUESTION_2_3_CHK CHECK (QUESTION_2_3 IN (0,50,60,80,95,100)),
    CONSTRAINT AE_QUESTION_2_4_CHK CHECK (QUESTION_2_4 IN (0,50,60,80,95,100)),
    CONSTRAINT AE_QUESTION_3_1_CHK CHECK (QUESTION_3_1 IN (0,50,60,80,95,100)),
    CONSTRAINT AE_QUESTION_3_2_CHK CHECK (QUESTION_3_2 IN (0,50,60,80,95,100)),
    CONSTRAINT AE_QUESTION_3_3_CHK CHECK (QUESTION_3_3 IN (0,50,60,80,95,100)),
    CONSTRAINT AE_QUESTION_3_4_CHK CHECK (QUESTION_3_4 IN (0,50,60,80,95,100)),
    CONSTRAINT AE_QUESTION_4_CHK   CHECK (QUESTION_4 = 1 OR QUESTION_4 = 0),
    CONSTRAINT AE_QUESTION_5_CHK CHECK (QUESTION_5 SIMILAR TO '^\[(I,)?(F,)?(J,)?(O,)?\]$'),
    CONSTRAINT AE_QUESTION_9_CHK CHECK (QUESTION_9 SIMILAR TO '^\[(P,)?(H,)?(C,)?(I,)?(O,)?\]$')
)
;



-- 
-- TABLE: ADMINISTRATOR 
--

CREATE TABLE ADMINISTRATOR(
    ADMINISTRATOR_ID     NUMERIC(10, 0)    NOT NULL DEFAULT ADMINISTRATOR_SEQ.NEXTVAL,
    NAME                 VARCHAR(100)    NOT NULL,
    LAST_NAME            VARCHAR(40)     NOT NULL,
    MOTHERS_LAST_NAME    VARCHAR(40),
    DEGREE               VARCHAR(40),
    GENDER               VARCHAR(1),
    JOB                  VARCHAR(1)      NOT NULL,
    CONSTRAINT ADMINISTRATOR_PK PRIMARY KEY (ADMINISTRATOR_ID),
    CONSTRAINT ADMINISTRATOR_GENDER_CHK CHECK (GENDER = 'M' OR GENDER = 'F'),
    CONSTRAINT ADMINISTRATOR_JOB_CHK CHECK (JOB IN ('C', 'CD', 'S', 'D'))
)
;



-- 
-- TABLE: CAREER 
--

CREATE TABLE CAREER(
    CAREER_ID    NUMERIC(10, 0)    NOT NULL DEFAULT CAREER_SEQ.NEXTVAL,
    NAME         VARCHAR(100)    NOT NULL,
    KEY          VARCHAR(30)     NOT NULL,
    CONSTRAINT CAREER_PK PRIMARY KEY (CAREER_ID),
    CONSTRAINT CAREER_KEY_UK UNIQUE (KEY)
)
;



-- 
-- TABLE: CATEGORY 
--

CREATE TABLE CATEGORY(
    CATEGORY_ID     NUMERIC(10, 0)    NOT NULL DEFAULT CATEGORY_SEQ.NEXTVAL,
    NAME            VARCHAR(50)     NOT NULL,
    ABBREVIATION    VARCHAR(20)     NOT NULL,
    CONSTRAINT CATEGORY_PK PRIMARY KEY (CATEGORY_ID)
)
;



-- 
-- TABLE: DEPARTMENT 
--

CREATE TABLE DEPARTMENT(
    DEPARTMENT_ID       NUMERIC(10, 0)    NOT NULL DEFAULT DEPARTMENT_SEQ.NEXTVAL,
    ABBREVIATION        VARCHAR(40)     NOT NULL,
    NAME                VARCHAR(100)    NOT NULL,
    ADMINISTRATOR_ID    NUMERIC(10, 0)    NOT NULL,
    CONSTRAINT DEPARTMENT_PK PRIMARY KEY (DEPARTMENT_ID)
)
;



-- 
-- TABLE: DIPLOMA 
--

CREATE TABLE DIPLOMA(
    DIPLOMA_ID    NUMERIC(20, 0)    NOT NULL DEFAULT DIPLOMA_SEQ.NEXTVAL,
    NAME          VARCHAR(300)    NOT NULL,
    CONSTRAINT DIPLOMA_PK PRIMARY KEY (DIPLOMA_ID)
)
;



-- 
-- TABLE: DIVISION 
--

CREATE TABLE DIVISION(
    DIVISION_ID     NUMERIC(10, 0)    NOT NULL DEFAULT DIVISION_SEQ.NEXTVAL,
    NAME            VARCHAR(60)     NOT NULL,
    ABBREVIATION    VARCHAR(30)     NOT NULL,
    CONSTRAINT DIVISION_PK PRIMARY KEY (DIVISION_ID)
)
;



-- 
-- TABLE: FACULTY 
--

CREATE TABLE FACULTY(
    FACULTY_ID    NUMERIC(10, 0)    NOT NULL DEFAULT FACULTY_SEQ.NEXTVAL,
    NAME          VARCHAR(50)     NOT NULL,
    CONSTRAINT FACULTY_PK PRIMARY KEY (FACULTY_ID)
)
;



-- 
-- TABLE: INSTRUCTOR 
--

CREATE TABLE INSTRUCTOR(
    INSTRUCTOR_ID    NUMERIC(40, 0)    NOT NULL DEFAULT INSTRUCTOR_SEQ.NEXTVAL,
    KEY              VARCHAR(10),
    SEND_DATE        DATE,
    PROFESSOR_ID     NUMERIC(40, 0)    NOT NULL,
    ACTIVITY_ID      NUMERIC(40, 0)    NOT NULL,
    CONSTRAINT INSTRUCTOR_PK PRIMARY KEY (INSTRUCTOR_ID),
    CONSTRAINT INSTRUCTOR_KEY_CHK CHECK (KEY SIMILAR TO '^F04[0-9]{4}[CTSDEF][0-9]{3}R[0-9]{4}$'),
    CONSTRAINT INSTRUCTOR_KEY_UK UNIQUE (KEY)
)
;



-- 
-- TABLE: INSTRUCTOR_EVALUATION 
--

CREATE TABLE INSTRUCTOR_EVALUATION(
    INSTRUCTOR_EVALUATION_ID    NUMERIC(40, 0)    NOT NULL DEFAULT INSTRUCTOR_EVALUATION_SEQ.NEXTVAL,
    QUESTION_1                  NUMERIC(2, 0),
    QUESTION_2                  NUMERIC(2, 0),
    QUESTION_3                  NUMERIC(2, 0),
    QUESTION_4                  NUMERIC(2, 0),
    QUESTION_5                  NUMERIC(2, 0),
    QUESTION_6                  NUMERIC(2, 0),
    QUESTION_7                  NUMERIC(2, 0),
    QUESTION_8                  NUMERIC(2, 0),
    QUESTION_9                  NUMERIC(2, 0),
    QUESTION_10                 NUMERIC(2, 0),
    QUESTION_11                 NUMERIC(2, 0),
    INSTRUCTOR_ID               NUMERIC(40, 0)    NOT NULL,
    PARTICIPANT_ID              NUMERIC(40, 0)    NOT NULL,
    CONSTRAINT INSTRUCTOR_EVALUATION_PK PRIMARY KEY (INSTRUCTOR_EVALUATION_ID),
    CONSTRAINT IE_QUESTION_1_CHK  CHECK (QUESTION_1 IN (0,50,60,80,95,100)),
    CONSTRAINT IE_QUESTION_2_CHK  CHECK (QUESTION_2 IN (0,50,60,80,95,100)),
    CONSTRAINT IE_QUESTION_3_CHK  CHECK (QUESTION_3 IN (0,50,60,80,95,100)),
    CONSTRAINT IE_QUESTION_4_CHK  CHECK (QUESTION_4 IN (0,50,60,80,95,100)),
    CONSTRAINT IE_QUESTION_5_CHK  CHECK (QUESTION_5 IN (0,50,60,80,95,100)),
    CONSTRAINT IE_QUESTION_6_CHK  CHECK (QUESTION_6 IN (0,50,60,80,95,100)),
    CONSTRAINT IE_QUESTION_7_CHK  CHECK (QUESTION_7 IN (0,50,60,80,95,100)),
    CONSTRAINT IE_QUESTION_8_CHK  CHECK (QUESTION_8 IN (0,50,60,80,95,100)),
    CONSTRAINT IE_QUESTION_9_CHK  CHECK (QUESTION_9 IN (0,50,60,80,95,100)),
    CONSTRAINT IE_QUESTION_10_CHK CHECK (QUESTION_10 IN (0,50,60,80,95,100)),
    CONSTRAINT IE_QUESTION_11_CHK CHECK (QUESTION_11 IN (0,50,60,80,95,100))
)
;



-- 
-- TABLE: PARTICIPANT 
--

CREATE TABLE PARTICIPANT(
    PARTICIPANT_ID    NUMERIC(40, 0)    NOT NULL DEFAULT PARTICIPANT_SEQ.NEXTVAL,
    ADDITIONAL        NUMERIC(1, 0)     NOT NULL,
    ATTENDANCE        NUMERIC(1, 0)     NOT NULL,
    ACCREDITED        NUMERIC(1, 0)     NOT NULL,
    CONFIRMATION      NUMERIC(1, 0)     NOT NULL,
    CANCELED          NUMERIC(1, 0)     NOT NULL,
    FREE              NUMERIC(1, 0)     NOT NULL,
    DISCOUNT          NUMERIC(4, 4)     NOT NULL,
    DEPOSIT           NUMERIC(10, 2)    NOT NULL,
    WL_WAS            NUMERIC(1, 0)     NOT NULL,
    WL_NUMERIC         NUMERIC,
    NAC               VARCHAR(300),
    GRADE             NUMERIC(2, 0),
    COMMENT           VARCHAR(300),
    KEY               VARCHAR(20),
    SEND_DATE         DATE,
    PROFESSOR_ID      NUMERIC(40, 0)    NOT NULL,
    ACTIVITY_ID       NUMERIC(40, 0)    NOT NULL,
    CONSTRAINT PARTICIPANT_PK PRIMARY KEY (PARTICIPANT_ID),
    CONSTRAINT PARTICIPANT_ADDITIONAL_CHK CHECK (ADDITIONAL = 1 OR ADDITIONAL = 0),
    CONSTRAINT PARTICIPANT_ATTENDANCE_CHK CHECK (ATTENDANCE = 1 OR ATTENDANCE = 0),
    CONSTRAINT PARTICIPANT_ACCREDITED_CHK CHECK (ACCREDITED = 1 OR ACCREDITED = 0),
    CONSTRAINT PARTICIPANT_CONFIRMATION_CHK CHECK (CONFIRMATION = 1 OR CONFIRMATION = 0),
    CONSTRAINT PARTICIPANT_CANCELED_CHK CHECK (CANCELED = 1 OR CANCELED = 0),
    CONSTRAINT PARTICIPANT_FREE_CHK CHECK (FREE = 1 OR FREE = 0),
    CONSTRAINT PARTICIPANT_WL_WAS_CHK CHECK (WL_WAS = 1 OR WL_WAS = 0),
    CONSTRAINT PARTICIPANT_DISCOUNT_CHK CHECK ((FREE = 1 AND DISCOUNT = 0) OR FREE = 0),
    CONSTRAINT PARTICIPANT_DEPOSIT_CHK CHECK ((FREE = 1 AND DEPOSIT = 0) OR FREE = 0),
    CONSTRAINT PARTICIPANT_KEY_CHK CHECK (KEY SIMILAR TO '^F04[0-9]{4}[CTSDEF][0-9]{3}C[0-9]{4}$')
)
;



-- 
-- TABLE: PROFESSOR 
--

CREATE TABLE PROFESSOR(
    PROFESSOR_ID         NUMERIC(40, 0)    NOT NULL DEFAULT PROFESSOR_SEQ.NEXTVAL,
    NAME                 VARCHAR(100)    NOT NULL,
    LAST_NAME            VARCHAR(50)     NOT NULL,
    MOTHERS_LAST_NAME    VARCHAR(50),
    RFC                  VARCHAR(25),
    WORKER_NUMERIC        VARCHAR(30),
    BIRTHDATE            DATE,
    PHONE_NUMERIC         VARCHAR(15),
    DEGREE               VARCHAR(40),
    EMAIL                VARCHAR(40),
    GENDER               VARCHAR(1),
    SEMBLANCE            VARCHAR(200),
    FACEBOOK             VARCHAR(40),
    IS_INSTRUCTOR        NUMERIC(1, 0)     NOT NULL,
    IS_UNAM              NUMERIC           NOT NULL,
    PROVENANCE           VARCHAR(100),
    CONSTRAINT PROFESSOR_PK PRIMARY KEY (PROFESSOR_ID),
    CONSTRAINT PROFESSOR_RFC_CHK CHECK (LENGTH(RFC) = 13 OR LENGTH(RFC) = 10),
    CONSTRAINT PROFESSOR_GENDER_CHK CHECK (GENDER = 'M' OR GENDER = 'F'),
    CONSTRAINT PROFESSOR_IS_INSTRUCTOR_CHK CHECK (IS_INSTRUCTOR = 1 OR IS_INSTRUCTOR = 0),
    CONSTRAINT PROFESSOR_IS_UNAM_CHK CHECK (IS_UNAM = 1 OR IS_UNAM = 0),
    CONSTRAINT PROFESSOR_PROVENANCE_CHK CHECK ((IS_UNAM = 0 AND PROVENANCE NOT NULL) OR IS_UNAM = 1),
    CONSTRAINT PROFESSOR_RFC_UK UNIQUE (RFC),
    CONSTRAINT PROFESSOR_WORKER_NUMERIC_UK UNIQUE (WORKER_NUMERIC)
)
;



-- 
-- TABLE: PROFESSOR_CAREER 
--

CREATE TABLE PROFESSOR_CAREER(
    PROFESSOR_CAREER_ID    NUMERIC(40, 0)    NOT NULL DEFAULT PROFESSOR_CAREER_SEQ.NEXTVAL,
    CAREER_ID              NUMERIC(10, 0)    NOT NULL,
    PROFESSOR_ID           NUMERIC(40, 0)    NOT NULL,
    CONSTRAINT PROFESSOR_CAREER_PK PRIMARY KEY (PROFESSOR_CAREER_ID)
)
;



-- 
-- TABLE: PROFESSOR_CATEGORY 
--

CREATE TABLE PROFESSOR_CATEGORY(
    PROFESSOR_CATEGORY_ID    NUMERIC(40, 0)    NOT NULL DEFAULT PROFESSOR_CATEGORY_SEQ.NEXTVAL,
    NUMERIC                   NUMERIC(1, 0)     NOT NULL,
    PROFESSOR_ID             NUMERIC(40, 0)    NOT NULL,
    CATEGORY_ID              NUMERIC(10, 0)    NOT NULL,
    CONSTRAINT PROFESSOR_CATEGORY_PK PRIMARY KEY (PROFESSOR_CATEGORY_ID)
)
;



-- 
-- TABLE: PROFESSOR_DIVISION 
--

CREATE TABLE PROFESSOR_DIVISION(
    PROFESSOR_DIVISION_ID    NUMERIC(40, 0)    NOT NULL DEFAULT PROFESSOR_DIVISION_SEQ.NEXTVAL,
    DIVISION_ID              NUMERIC(10, 0)    NOT NULL,
    PROFESSOR_ID             NUMERIC(40, 0)    NOT NULL,
    CONSTRAINT PROFESSOR_DIVISION_PK PRIMARY KEY (PROFESSOR_DIVISION_ID)
)
;



-- 
-- TABLE: PROFESSOR_FACULTY 
--

CREATE TABLE PROFESSOR_FACULTY(
    PROFESSOR_FACULTY_ID    VARCHAR(40)     NOT NULL DEFAULT PROFESSOR_FACULTY_SEQ.NEXTVAL,
    PROFESSOR_ID            NUMERIC(40, 0)    NOT NULL,
    FACULTY_ID              NUMERIC(10, 0)    NOT NULL,
    CONSTRAINT PROFESSOR_FACULTY_PK PRIMARY KEY (PROFESSOR_FACULTY_ID)

)
;



-- 
-- TABLE: SEMINAR_TOPIC 
--

CREATE TABLE SEMINAR_TOPIC(
    SEMINAR_TOPIC_ID    VARCHAR(40)     NOT NULL DEFAULT SEMINAR_TOPIC_SEQ.NEXTVAL,
    NAME                VARCHAR(300)    NOT NULL,
    HOURS               NUMERIC(3, 0)     NOT NULL,
    EX_DATE             VARCHAR(40)     NOT NULL,
    INSTRUCTOR_ID       NUMERIC(40, 0)    NOT NULL,
    ACTIVITY_ID         NUMERIC(40, 0)    NOT NULL,
    CONSTRAINT SEMINAR_TOPIC_PK PRIMARY KEY (SEMINAR_TOPIC_ID)
)
;



-- 
-- TABLE: USER 
--

CREATE TABLE USER(
    USER_ID          NUMERIC(40, 0)    NOT NULL DEFAULT USER_SEQ.NEXTVAL,
    NAME             VARCHAR(50)     NOT NULL,
    USERNAME         VARCHAR(40)     NOT NULL,
    PASSWORD         VARCHAR(40)     NOT NULL,
    ADMIN            NUMERIC(1, 0)     NOT NULL,
    DEPARTMENT_ID    NUMERIC(10, 0),
    CONSTRAINT USER_PK PRIMARY KEY (USER_ID),
    CONSTRAINT USER_ADMIN_CHK CHECK (ADMIN = 1 OR ADMIN = 0),
    CONSTRAINT USER_USERNAME_UK UNIQUE (USERNAME)
)
;



-- 
-- TABLE: VENUE 
--

CREATE TABLE VENUE(
    VENUE_ID    NUMERIC(20, 0)    NOT NULL DEFAULT VENUE_SEQ.NEXTVAL,
    NAME        VARCHAR(100)    NOT NULL,
    CAPACITY    NUMERIC(20, 0)    NOT NULL,
    LOCATION    VARCHAR(200)    NOT NULL,
    CONSTRAINT VENUE_PK PRIMARY KEY (VENUE_ID),
    CONSTRAINT VENUE_CAPACITY_CHK CHECK (CAPACITY > 0)
)
;

\qecho ================== ADDING FOREIGN KEYS ==================

-- 
-- TABLE: ACTIVITY 
--

ALTER TABLE ACTIVITY ADD CONSTRAINT ACTIVITY_VENUE_ID_FK
    FOREIGN KEY (VENUE_ID)
    REFERENCES VENUE(VENUE_ID)
;

ALTER TABLE ACTIVITY ADD CONSTRAINT ACTIVITY_ACTIVITY_CATALOGUE_ID_FK
    FOREIGN KEY (ACTIVITY_CATALOGUE_ID)
    REFERENCES ACTIVITY_CATALOGUE(ACTIVITY_CATALOGUE_ID)
;


-- 
-- TABLE: ACTIVITY_CATALOGUE 
--

ALTER TABLE ACTIVITY_CATALOGUE ADD CONSTRAINT ACTIVITY_CATALOGUE_DEPARTMENT_ID_FK
    FOREIGN KEY (DEPARTMENT_ID)
    REFERENCES DEPARTMENT(DEPARTMENT_ID)
;

ALTER TABLE ACTIVITY_CATALOGUE ADD CONSTRAINT ACTIVITY_CATALOGUE_DIPLOMA_ID_FK
    FOREIGN KEY (DIPLOMA_ID)
    REFERENCES DIPLOMA(DIPLOMA_ID)
;


-- 
-- TABLE: ACTIVITY_EVALUATION 
--

ALTER TABLE ACTIVITY_EVALUATION ADD CONSTRAINT ACTIVITY_EVALUATION_PARTICIPANT_ID_FK
    FOREIGN KEY (PARTICIPANT_ID)
    REFERENCES PARTICIPANT(PARTICIPANT_ID)
;


-- 
-- TABLE: DEPARTMENT 
--

ALTER TABLE DEPARTMENT ADD CONSTRAINT DEPARTMENT_ADMINISTRATOR_ID_FK
    FOREIGN KEY (ADMINISTRATOR_ID)
    REFERENCES ADMINISTRATOR(ADMINISTRATOR_ID)
;


-- 
-- TABLE: INSTRUCTOR 
--

ALTER TABLE INSTRUCTOR ADD CONSTRAINT INSTRUCTOR_PROFESSOR_ID_FK
    FOREIGN KEY (PROFESSOR_ID)
    REFERENCES PROFESSOR(PROFESSOR_ID)
;

ALTER TABLE INSTRUCTOR ADD CONSTRAINT INSTRUCTOR_ACTIVITY_ID_FK 
    FOREIGN KEY (ACTIVITY_ID)
    REFERENCES ACTIVITY(ACTIVITY_ID)
;


-- 
-- TABLE: INSTRUCTOR_EVALUATION 
--

ALTER TABLE INSTRUCTOR_EVALUATION ADD CONSTRAINT INSTRUCTOR_EVALUATION_INSTRUCTOR_ID_FK
    FOREIGN KEY (INSTRUCTOR_ID)
    REFERENCES INSTRUCTOR(INSTRUCTOR_ID)
;

ALTER TABLE INSTRUCTOR_EVALUATION ADD CONSTRAINT INSTRUCTOR_EVALUATION_PARTICIPANT_ID_FK
    FOREIGN KEY (PARTICIPANT_ID)
    REFERENCES PARTICIPANT(PARTICIPANT_ID)
;


-- 
-- TABLE: PARTICIPANT 
--

ALTER TABLE PARTICIPANT ADD CONSTRAINT PARTICIPANT_PROFESSOR_ID_FK
    FOREIGN KEY (PROFESSOR_ID)
    REFERENCES PROFESSOR(PROFESSOR_ID)
;

ALTER TABLE PARTICIPANT ADD CONSTRAINT PARTICIPANT_ACTIVITY_ID_FK
    FOREIGN KEY (ACTIVITY_ID)
    REFERENCES ACTIVITY(ACTIVITY_ID)
;


-- 
-- TABLE: PROFESSOR_CAREER 
--

ALTER TABLE PROFESSOR_CAREER ADD CONSTRAINT PROFESSOR_CAREER_CAREER_ID_FK
    FOREIGN KEY (CAREER_ID)
    REFERENCES CAREER(CAREER_ID)
;

ALTER TABLE PROFESSOR_CAREER ADD CONSTRAINT PROFESSOR_CARREER_PROFESSOR_ID_FK
    FOREIGN KEY (PROFESSOR_ID)
    REFERENCES PROFESSOR(PROFESSOR_ID)
;


-- 
-- TABLE: PROFESSOR_CATEGORY 
--

ALTER TABLE PROFESSOR_CATEGORY ADD CONSTRAINT PROFESSOR_CATEGORY_CATEGORY_ID_FK
    FOREIGN KEY (CATEGORY_ID)
    REFERENCES CATEGORY(CATEGORY_ID)
;

ALTER TABLE PROFESSOR_CATEGORY ADD CONSTRAINT PROFESSOR_CATEGORY_PROFESSOR_ID_FK
    FOREIGN KEY (PROFESSOR_ID)
    REFERENCES PROFESSOR(PROFESSOR_ID)
;


-- 
-- TABLE: PROFESSOR_DIVISION 
--

ALTER TABLE PROFESSOR_DIVISION ADD CONSTRAINT PROFESSOR_DIVISION_DIVISION_ID_FK
    FOREIGN KEY (DIVISION_ID)
    REFERENCES DIVISION(DIVISION_ID)
;

ALTER TABLE PROFESSOR_DIVISION ADD CONSTRAINT PROFESSOR_DIVISION_PROFESSOR_ID_FK 
    FOREIGN KEY (PROFESSOR_ID)
    REFERENCES PROFESSOR(PROFESSOR_ID)
;


-- 
-- TABLE: PROFESSOR_FACULTY 
--

ALTER TABLE PROFESSOR_FACULTY ADD CONSTRAINT PROFESSOR_FACULTY_PROFESSOR_ID_FK
    FOREIGN KEY (PROFESSOR_ID)
    REFERENCES PROFESSOR(PROFESSOR_ID)
;

ALTER TABLE PROFESSOR_FACULTY ADD CONSTRAINT PROFESSOR_FACULTY_FACULTY_ID_FK
    FOREIGN KEY (FACULTY_ID)
    REFERENCES FACULTY(FACULTY_ID)
;


-- 
-- TABLE: SEMINAR_TOPIC 
--

ALTER TABLE SEMINAR_TOPIC ADD CONSTRAINT SEMINAR_TOPIC_INSTRUCTOR_ID_FK 
    FOREIGN KEY (INSTRUCTOR_ID)
    REFERENCES INSTRUCTOR(INSTRUCTOR_ID)
;

ALTER TABLE SEMINAR_TOPIC ADD CONSTRAINT SEMINAR_TOPIC_ACTIVITY_ID_FK
    FOREIGN KEY (ACTIVITY_ID)
    REFERENCES ACTIVITY(ACTIVITY_ID)
;


-- 
-- TABLE: USER 
--

ALTER TABLE USER ADD CONSTRAINT USER_DEPARTMENT_ID_FK
    FOREIGN KEY (DEPARTMENT_ID)
    REFERENCES DEPARTMENT(DEPARTMENT_ID)
;