--
-- Company :      UNAM
-- Project :      MagestiCD
-- Author :       C. Mauricio Ramos V.,
--                Carolina Kennedy V.
--
-- Date Created : Monday, May 23, 2022 16:10:58
-- Target DBMS : Postgres 14
--
-- Description : Sequencies creation (DDL) for the ID's
--

\qecho ================== DROPPING OLD SEQUENCIES ==================

DROP SEQUENCE ACTIVITY_SEQ
;
DROP SEQUENCE ACTIVITY_CATALOGUE_SEQ
;
DROP SEQUENCE ACTIVITY_EVALUATION_SEQ
;
DROP SEQUENCE ADMINISTRATOR_SEQ
;
DROP SEQUENCE CAREER_SEQ
;
DROP SEQUENCE CATEGORY_SEQ
;
DROP SEQUENCE DEPARTMENT_SEQ
;
DROP SEQUENCE DIPLOMA_SEQ
;
DROP SEQUENCE DIVISION_SEQ
;
DROP SEQUENCE FACULTY_SEQ
;
DROP SEQUENCE INSTRUCTOR_SEQ
;
DROP SEQUENCE INSTRUCTOR_EVALUATION_SEQ
;
DROP SEQUENCE PARTICIPANT_SEQ
;
DROP SEQUENCE PROFESSOR_SEQ
;
DROP SEQUENCE PROFESSOR_CAREER_SEQ
;
DROP SEQUENCE PROFESSOR_CATEGORY_SEQ
;
DROP SEQUENCE PROFESSOR_DIVISION_SEQ
;
DROP SEQUENCE PROFESSOR_FACULTY_SEQ
;
DROP SEQUENCE SEMINAR_TOPIC_SEQ
;
DROP SEQUENCE USER_SEQ
;
DROP SEQUENCE VENUE_SEQ
;



\qecho ================== CREATING SEQUENCIES ==================

CREATE SEQUENCE ACTIVITY_SEQ
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    NO CYCLE
    OWNED BY ACTIVITY.ACTIVITY_ID
;

CREATE SEQUENCE ACTIVITY_CATALOGUE_SEQ
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    NO CYCLE
    OWNED BY ACTIVITY_CATALOGUE.ACTIVITY_CATALOGUE_ID
;

CREATE SEQUENCE ACTIVITY_EVALUATION_SEQ
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    NO CYCLE
    OWNED BY ACTIVITY_EVALUATION.ACTIVITY_EVALUATION_ID
;

CREATE SEQUENCE ADMINISTRATOR_SEQ
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    NO CYCLE
    OWNED BY ADMINISTRATOR.ADMINISTRATOR_ID
;

CREATE SEQUENCE CAREER_SEQ
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    NO CYCLE
    OWNED BY CAREER.CAREER_ID
;

CREATE SEQUENCE CATEGORY_SEQ
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    NO CYCLE
    OWNED BY CATEGORY.CATEGORY_ID
;

CREATE SEQUENCE DEPARTMENT_SEQ
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    NO CYCLE
    OWNED BY DEPARTMENT.DEPARTMENT_ID
;

CREATE SEQUENCE DIPLOMA_SEQ
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    NO CYCLE
    OWNED BY DIPLOMA.DIPLOMA_ID
;

CREATE SEQUENCE DIVISION_SEQ
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    NO CYCLE
    OWNED BY DIVISION.DIVISION_ID
;

CREATE SEQUENCE FACULTY_SEQ
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    NO CYCLE
    OWNED BY FACULTY.FACULTY_ID
;

CREATE SEQUENCE INSTRUCTOR_SEQ
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    NO CYCLE
    OWNED BY INSTRUCTOR.INSTRUCTOR_ID
;

CREATE SEQUENCE INSTRUCTOR_EVALUATION_SEQ
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    NO CYCLE
    OWNED BY INSTRUCTOR_EVALUATION.INSTRUCTOR_EVALUATION_ID
;

CREATE SEQUENCE PARTICIPANT_SEQ
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    NO CYCLE
    OWNED BY PARTICIPANT.PARTICIPANT_ID
;

CREATE SEQUENCE PROFESSOR_SEQ
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    NO CYCLE
    OWNED BY PROFESSOR.PROFESSOR_ID
;

CREATE SEQUENCE PROFESSOR_CAREER_SEQ
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    NO CYCLE
    OWNED BY PROFESSOR_CAREER.PROFESSOR_CAREER_ID
;

CREATE SEQUENCE PROFESSOR_CATEGORY_SEQ
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    NO CYCLE
    OWNED BY PROFESSOR_CATEGORY.PROFESSOR_CATEGORY_ID
;

CREATE SEQUENCE PROFESSOR_DIVISION_SEQ
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    NO CYCLE
    OWNED BY PROFESSOR_DIVISION.PROFESSOR_DIVISION_ID
;

CREATE SEQUENCE PROFESSOR_FACULTY_SEQ
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    NO CYCLE
    OWNED BY PROFESSOR_FACULTY.PROFESSOR_FACULTY_ID
;

CREATE SEQUENCE SEMINAR_TOPIC_SEQ
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    NO CYCLE
    OWNED BY SEMINAR_TOPIC.SEMINAR_TOPIC_ID
;

CREATE SEQUENCE USER_SEQ
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    NO CYCLE
    OWNED BY ACCOUNT.ACCOUNT_ID
;

CREATE SEQUENCE VENUE_SEQ
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    NO CYCLE
    OWNED BY VENUE.VENUE_ID
;