\i ./s-04-dml-division.sql
\i ./s-04-dml-career.sql
\i ./s-04-dml-category.sql
\i ./s-04-dml-faculty.sql
\i ./s-04-dml-administrator.sql
\i ./s-04-dml-department.sql
\i ./s-04-dml-account.sql
\i ./s-04-dml-venue.sql
\i ./s-04-dml-professor.sql
\i ./s-04-dml-activity_catalogue.sql