\qecho ================== INSERTING INTO PARTICIPANT ==================

INSERT INTO
  PARTICIPANT (PARTICIPANT_ID, PROFESSOR_ID, ACTIVITY_ID)
VALUES
  (
    NEXTVAL('PARTICIPANT_SEQ'),
    13,
    1
  );

INSERT INTO
  PARTICIPANT (PARTICIPANT_ID, PROFESSOR_ID, ACTIVITY_ID)
VALUES
  (
    NEXTVAL('PARTICIPANT_SEQ'),
    44,
    1
  );

INSERT INTO
  PARTICIPANT (PARTICIPANT_ID, PROFESSOR_ID, ACTIVITY_ID)
VALUES
  (
    NEXTVAL('PARTICIPANT_SEQ'),
    9,
    1
  );

INSERT INTO
  PARTICIPANT (PARTICIPANT_ID, PROFESSOR_ID, ACTIVITY_ID)
VALUES
  (
    NEXTVAL('PARTICIPANT_SEQ'),
    11,
    1
  );

INSERT INTO
  PARTICIPANT (PARTICIPANT_ID, PROFESSOR_ID, ACTIVITY_ID)
VALUES
  (
    NEXTVAL('PARTICIPANT_SEQ'),
    32,
    1
  );  

INSERT INTO
  PARTICIPANT (PARTICIPANT_ID, PROFESSOR_ID, ACTIVITY_ID)
VALUES
  (
    NEXTVAL('PARTICIPANT_SEQ'),
    27,
    1
  ); 

INSERT INTO
  PARTICIPANT (PARTICIPANT_ID, PROFESSOR_ID, ACTIVITY_ID)
VALUES
  (
    NEXTVAL('PARTICIPANT_SEQ'),
    17,
    1
  );

INSERT INTO
  PARTICIPANT (PARTICIPANT_ID, PROFESSOR_ID, ACTIVITY_ID)
VALUES
  (
    NEXTVAL('PARTICIPANT_SEQ'),
    3,
    1
  );

INSERT INTO
  PARTICIPANT (PARTICIPANT_ID, PROFESSOR_ID, ACTIVITY_ID)
VALUES
  (
    NEXTVAL('PARTICIPANT_SEQ'),
    21,
    1
  );

INSERT INTO
  PARTICIPANT (PARTICIPANT_ID, PROFESSOR_ID, ACTIVITY_ID)
VALUES
  (
    NEXTVAL('PARTICIPANT_SEQ'),
    23,
    1
  );

------
INSERT INTO
  PARTICIPANT (PARTICIPANT_ID, PROFESSOR_ID, ACTIVITY_ID)
VALUES
  (
    NEXTVAL('PARTICIPANT_SEQ'),
    13,
    2
  );

INSERT INTO
  PARTICIPANT (PARTICIPANT_ID, PROFESSOR_ID, ACTIVITY_ID)
VALUES
  (
    NEXTVAL('PARTICIPANT_SEQ'),
    44,
    2
  );

INSERT INTO
  PARTICIPANT (PARTICIPANT_ID, PROFESSOR_ID, ACTIVITY_ID)
VALUES
  (
    NEXTVAL('PARTICIPANT_SEQ'),
    9,
    2
  );

INSERT INTO
  PARTICIPANT (PARTICIPANT_ID, PROFESSOR_ID, ACTIVITY_ID)
VALUES
  (
    NEXTVAL('PARTICIPANT_SEQ'),
    11,
    2
  );

INSERT INTO
  PARTICIPANT (PARTICIPANT_ID, PROFESSOR_ID, ACTIVITY_ID)
VALUES
  (
    NEXTVAL('PARTICIPANT_SEQ'),
    32,
    2
  );  

INSERT INTO
  PARTICIPANT (PARTICIPANT_ID, PROFESSOR_ID, ACTIVITY_ID)
VALUES
  (
    NEXTVAL('PARTICIPANT_SEQ'),
    27,
    2
  ); 

INSERT INTO
  PARTICIPANT (PARTICIPANT_ID, PROFESSOR_ID, ACTIVITY_ID)
VALUES
  (
    NEXTVAL('PARTICIPANT_SEQ'),
    17,
    2
  );

INSERT INTO
  PARTICIPANT (PARTICIPANT_ID, PROFESSOR_ID, ACTIVITY_ID)
VALUES
  (
    NEXTVAL('PARTICIPANT_SEQ'),
    3,
    2
  );

INSERT INTO
  PARTICIPANT (PARTICIPANT_ID, PROFESSOR_ID, ACTIVITY_ID)
VALUES
  (
    NEXTVAL('PARTICIPANT_SEQ'),
    21,
    2
  );

INSERT INTO
  PARTICIPANT (PARTICIPANT_ID, PROFESSOR_ID, ACTIVITY_ID)
VALUES
  (
    NEXTVAL('PARTICIPANT_SEQ'),
    23,
    2
  );

------
INSERT INTO
  PARTICIPANT (PARTICIPANT_ID, PROFESSOR_ID, ACTIVITY_ID)
VALUES
  (
    NEXTVAL('PARTICIPANT_SEQ'),
    13,
    3
  );

INSERT INTO
  PARTICIPANT (PARTICIPANT_ID, PROFESSOR_ID, ACTIVITY_ID)
VALUES
  (
    NEXTVAL('PARTICIPANT_SEQ'),
    44,
    3
  );

INSERT INTO
  PARTICIPANT (PARTICIPANT_ID, PROFESSOR_ID, ACTIVITY_ID)
VALUES
  (
    NEXTVAL('PARTICIPANT_SEQ'),
    9,
    3
  );

INSERT INTO
  PARTICIPANT (PARTICIPANT_ID, PROFESSOR_ID, ACTIVITY_ID)
VALUES
  (
    NEXTVAL('PARTICIPANT_SEQ'),
    11,
    3
  );

INSERT INTO
  PARTICIPANT (PARTICIPANT_ID, PROFESSOR_ID, ACTIVITY_ID)
VALUES
  (
    NEXTVAL('PARTICIPANT_SEQ'),
    32,
    3
  );  

INSERT INTO
  PARTICIPANT (PARTICIPANT_ID, PROFESSOR_ID, ACTIVITY_ID)
VALUES
  (
    NEXTVAL('PARTICIPANT_SEQ'),
    27,
    3
  ); 

INSERT INTO
  PARTICIPANT (PARTICIPANT_ID, PROFESSOR_ID, ACTIVITY_ID)
VALUES
  (
    NEXTVAL('PARTICIPANT_SEQ'),
    17,
    3
  );

INSERT INTO
  PARTICIPANT (PARTICIPANT_ID, PROFESSOR_ID, ACTIVITY_ID)
VALUES
  (
    NEXTVAL('PARTICIPANT_SEQ'),
    3,
    3
  );

INSERT INTO
  PARTICIPANT (PARTICIPANT_ID, PROFESSOR_ID, ACTIVITY_ID)
VALUES
  (
    NEXTVAL('PARTICIPANT_SEQ'),
    21,
    3
  );

INSERT INTO
  PARTICIPANT (PARTICIPANT_ID, PROFESSOR_ID, ACTIVITY_ID)
VALUES
  (
    NEXTVAL('PARTICIPANT_SEQ'),
    23,
    3
  );