\qecho ================== INSERTING INTO ACTIVITY CATALOGUE ==================

INSERT INTO
  ACTIVITY_CATALOGUE (ACTIVITY_CATALOGUE_ID, KEY, NAME, HOURS, TYPE, INSTITUTION, CREATION_DATE, DEPARTMENT_ID)
VALUES
  (
    NEXTVAL('ACTIVITY_CATALOGUE_SEQ'),
    'DHCU178',
    'Salud Emocional',
    8,
    'CT',
    'CDD',
    '2022-02-05',
    5
  );

INSERT INTO
  ACTIVITY_CATALOGUE (ACTIVITY_CATALOGUE_ID, KEY, NAME, HOURS, TYPE, INSTITUTION, CREATION_DATE, DEPARTMENT_ID)
VALUES
  (
    NEXTVAL('ACTIVITY_CATALOGUE_SEQ'),
    'COCU129',
    'Access básico',
    15,
    'CT',
    'CDD',
    '2018-05-18',
    2
  );

INSERT INTO
  ACTIVITY_CATALOGUE (ACTIVITY_CATALOGUE_ID, KEY, NAME, HOURS, TYPE, INSTITUTION, CREATION_DATE, DEPARTMENT_ID)
VALUES
  (
    NEXTVAL('ACTIVITY_CATALOGUE_SEQ'),
    'COCU021',
    'Access',
    12,
    'CT',
    'CDD',
    '2018-05-18',
    2
  );

INSERT INTO
  ACTIVITY_CATALOGUE (ACTIVITY_CATALOGUE_ID, KEY, NAME, HOURS, TYPE, INSTITUTION, CREATION_DATE, DEPARTMENT_ID)
VALUES
  (
    NEXTVAL('ACTIVITY_CATALOGUE_SEQ'),
    'COCU041',
    'Actualización a Office 2007',
    12,
    'CT',
    'CDD',
    '2018-05-18',
    2
  );

INSERT INTO
  ACTIVITY_CATALOGUE (ACTIVITY_CATALOGUE_ID, KEY, NAME, HOURS, TYPE, INSTITUTION, CREATION_DATE, DEPARTMENT_ID)
VALUES
  (
    NEXTVAL('ACTIVITY_CATALOGUE_SEQ'),
    'VNADIDGAPA',
    'La violencia no visible en el aula: Detección e intervención',
    20,
    'CU',
    'DGAPA',
    '2012-12-12',
    5
  );

INSERT INTO
  ACTIVITY_CATALOGUE (ACTIVITY_CATALOGUE_ID, KEY, NAME, HOURS, TYPE, INSTITUTION, CREATION_DATE, DEPARTMENT_ID)
VALUES
  (
    NEXTVAL('ACTIVITY_CATALOGUE_SEQ'),
    'DHCU157',
    'Comunicación asertiva en el aula. Parte 2',
    20,
    'CU',
    'DGAPA',
    '2012-12-12',
    5
  );

INSERT INTO
  ACTIVITY_CATALOGUE (ACTIVITY_CATALOGUE_ID, KEY, NAME, HOURS, TYPE, INSTITUTION, CREATION_DATE, DEPARTMENT_ID)
VALUES
  (
    NEXTVAL('ACTIVITY_CATALOGUE_SEQ'),
    'ED1HCZ12',
    'Ecuaciones Diferenciales',
    20,
    'SE',
    'DGAPA',
    '2018-05-18',
    4
  );