\qecho ================== INSERTING INTO CATEGORY ==================

INSERT INTO
  CATEGORY (CATEGORY_ID, NAME, ABBREVIATION)
VALUES
  (
    NEXTVAL('CATEGORY_SEQ'),
    'Administrativo',
    'ADM'
  );

INSERT INTO
  CATEGORY (CATEGORY_ID, NAME, ABBREVIATION)
VALUES
  (
    NEXTVAL('CATEGORY_SEQ'),
    'Ayudante de profesor A',
    'AYTE PROF A'
  );

INSERT INTO
  CATEGORY (CATEGORY_ID, NAME, ABBREVIATION)
VALUES
  (
    NEXTVAL('CATEGORY_SEQ'),
    'Ayudante de profesor B',
    'AYTE PROF B'
  );

INSERT INTO
  CATEGORY (CATEGORY_ID, NAME, ABBREVIATION)
VALUES
  (
    NEXTVAL('CATEGORY_SEQ'),
    'Funcionario',
    'FUNC'
  );

INSERT INTO
  CATEGORY (CATEGORY_ID, NAME, ABBREVIATION)
VALUES
  (
    NEXTVAL('CATEGORY_SEQ'),
    'Investigador Asociado B TC',
    'INV ASOC B TC'
  );

INSERT INTO
  CATEGORY (CATEGORY_ID, NAME, ABBREVIATION)
VALUES
  (
    NEXTVAL('CATEGORY_SEQ'),
    'Investigador titular A TC',
    'INV TIT A T C'
  );

INSERT INTO
  CATEGORY (CATEGORY_ID, NAME, ABBREVIATION)
VALUES
  (
    NEXTVAL('CATEGORY_SEQ'),
    'Investigador titular B MT',
    'INV TIT B M  T'
  );

INSERT INTO
  CATEGORY (CATEGORY_ID, NAME, ABBREVIATION)
VALUES
  (
    NEXTVAL('CATEGORY_SEQ'),
    'Investigador titular B TC',
    'INV TIT B T  C'
  );

INSERT INTO
  CATEGORY (CATEGORY_ID, NAME, ABBREVIATION)
VALUES
  (
    NEXTVAL('CATEGORY_SEQ'),
    'Investigador titular C MT',
    'INV TIT C M  T'
  );

INSERT INTO
  CATEGORY (CATEGORY_ID, NAME, ABBREVIATION)
VALUES
  (
    NEXTVAL('CATEGORY_SEQ'),
    'Investigador titular C TC',
    'INV TIT C T  C'
  );

INSERT INTO
  CATEGORY (CATEGORY_ID, NAME, ABBREVIATION)
VALUES
  (
    NEXTVAL('CATEGORY_SEQ'),
    'Profesor Emérito',
    'PROF EMERITO'
  );

INSERT INTO
  CATEGORY (CATEGORY_ID, NAME, ABBREVIATION)
VALUES
  (
    NEXTVAL('CATEGORY_SEQ'),
    'Profesor de Asignatura A',
    'PROF ASG A'
  );

INSERT INTO
  CATEGORY (CATEGORY_ID, NAME, ABBREVIATION)
VALUES
  (
    NEXTVAL('CATEGORY_SEQ'),
    'Profesor de Asignatura B',
    'PROF ASG B'
  );

INSERT INTO
  CATEGORY (CATEGORY_ID, NAME, ABBREVIATION)
VALUES
  (
    NEXTVAL('CATEGORY_SEQ'),
    'Profesor Titular A TC',
    'PROF TIT A T C'
  );

INSERT INTO
  CATEGORY (CATEGORY_ID, NAME, ABBREVIATION)
VALUES
  (
    NEXTVAL('CATEGORY_SEQ'),
    'Profesor Titular B TC',
    'PROF TIT B T C'
  );

INSERT INTO
  CATEGORY (CATEGORY_ID, NAME, ABBREVIATION)
VALUES
  (
    NEXTVAL('CATEGORY_SEQ'),
    'Profesor Titular C TC',
    'PROF TIT C T C'
  );

INSERT INTO
  CATEGORY (CATEGORY_ID, NAME, ABBREVIATION)
VALUES
  (
    NEXTVAL('CATEGORY_SEQ'),
    'Técnico Asociado A TC',
    'TEC ASOC A T C'
  );

INSERT INTO
  CATEGORY (CATEGORY_ID, NAME, ABBREVIATION)
VALUES
  (
    NEXTVAL('CATEGORY_SEQ'),
    'Técnico Asociado B TC',
    'TEC ASOC B T C'
  );

INSERT INTO
  CATEGORY (CATEGORY_ID, NAME, ABBREVIATION)
VALUES
  (
    NEXTVAL('CATEGORY_SEQ'),
    'Técnico Asociado C TC',
    'TEC ASOC C T C'
  );

INSERT INTO
  CATEGORY (CATEGORY_ID, NAME, ABBREVIATION)
VALUES
  (
    NEXTVAL('CATEGORY_SEQ'),
    'Técnico Auxiliar A TC',
    'TEC AUX A T C'
  );

INSERT INTO
  CATEGORY (CATEGORY_ID, NAME, ABBREVIATION)
VALUES
  (
    NEXTVAL('CATEGORY_SEQ'),
    'Técnico Auxiliar B MT',
    'TEC AUX B M T'
  );

INSERT INTO
  CATEGORY (CATEGORY_ID, NAME, ABBREVIATION)
VALUES
  (
    NEXTVAL('CATEGORY_SEQ'),
    'Técnico Auxiliar B TC',
    'TEC AUX B T C'
  );

INSERT INTO
  CATEGORY (CATEGORY_ID, NAME, ABBREVIATION)
VALUES
  (
    NEXTVAL('CATEGORY_SEQ'),
    'Técnico Auxiliar C TC',
    'TEC AUX C T C'
  );

INSERT INTO
  CATEGORY (CATEGORY_ID, NAME, ABBREVIATION)
VALUES
  (
    NEXTVAL('CATEGORY_SEQ'),
    'Técnico Titular A TC',
    'TEC TIT A T C'
  );

INSERT INTO
  CATEGORY (CATEGORY_ID, NAME, ABBREVIATION)
VALUES
  (
    NEXTVAL('CATEGORY_SEQ'),
    'Técnico Titular B TC',
    'TEC TIT B T C'
  );

INSERT INTO
  CATEGORY (CATEGORY_ID, NAME, ABBREVIATION)
VALUES
  (
    NEXTVAL('CATEGORY_SEQ'),
    'Técnico Titular C TC',
    'TEC TIT C T C'
  );