\qecho ================== INSERTING INTO INSTRUCTOR ==================

INSERT INTO
  INSTRUCTOR (INSTRUCTOR_ID, PROFESSOR_ID, ACTIVITY_ID)
VALUES
  (
    NEXTVAL('INSTRUCTOR_SEQ'),
    29,
    1
  );

INSERT INTO
  INSTRUCTOR (INSTRUCTOR_ID, PROFESSOR_ID, ACTIVITY_ID)
VALUES
  (
    NEXTVAL('INSTRUCTOR_SEQ'),
    30,
    1
  );

INSERT INTO
  INSTRUCTOR (INSTRUCTOR_ID, PROFESSOR_ID, ACTIVITY_ID)
VALUES
  (
    NEXTVAL('INSTRUCTOR_SEQ'),
    47,
    2
  );

INSERT INTO
  INSTRUCTOR (INSTRUCTOR_ID, PROFESSOR_ID, ACTIVITY_ID)
VALUES
  (
    NEXTVAL('INSTRUCTOR_SEQ'),
    35,
    2
  );

INSERT INTO
  INSTRUCTOR (INSTRUCTOR_ID, PROFESSOR_ID, ACTIVITY_ID)
VALUES
  (
    NEXTVAL('INSTRUCTOR_SEQ'),
    46,
    3
  );

INSERT INTO
  INSTRUCTOR (INSTRUCTOR_ID, PROFESSOR_ID, ACTIVITY_ID)
VALUES
  (
    NEXTVAL('INSTRUCTOR_SEQ'),
    1,
    4
  );

INSERT INTO
  INSTRUCTOR (INSTRUCTOR_ID, PROFESSOR_ID, ACTIVITY_ID)
VALUES
  (
    NEXTVAL('INSTRUCTOR_SEQ'),
    2,
    5
  );

INSERT INTO
  INSTRUCTOR (INSTRUCTOR_ID, PROFESSOR_ID, ACTIVITY_ID)
VALUES
  (
    NEXTVAL('INSTRUCTOR_SEQ'),
    3,
    6
  );

INSERT INTO
  INSTRUCTOR (INSTRUCTOR_ID, PROFESSOR_ID, ACTIVITY_ID)
VALUES
  (
    NEXTVAL('INSTRUCTOR_SEQ'),
    4,
    7
  );

INSERT INTO
  INSTRUCTOR (INSTRUCTOR_ID, PROFESSOR_ID, ACTIVITY_ID)
VALUES
  (
    NEXTVAL('INSTRUCTOR_SEQ'),
    5,
    8
  );

INSERT INTO
  INSTRUCTOR (INSTRUCTOR_ID, PROFESSOR_ID, ACTIVITY_ID)
VALUES
  (
    NEXTVAL('INSTRUCTOR_SEQ'),
    6,
    9
  );

INSERT INTO
  INSTRUCTOR (INSTRUCTOR_ID, PROFESSOR_ID, ACTIVITY_ID)
VALUES
  (
    NEXTVAL('INSTRUCTOR_SEQ'),
    7,
    10
  );

INSERT INTO
  INSTRUCTOR (INSTRUCTOR_ID, PROFESSOR_ID, ACTIVITY_ID)
VALUES
  (
    NEXTVAL('INSTRUCTOR_SEQ'),
    7,
    11
  );

INSERT INTO
  INSTRUCTOR (INSTRUCTOR_ID, PROFESSOR_ID, ACTIVITY_ID)
VALUES
  (
    NEXTVAL('INSTRUCTOR_SEQ'),
    7,
    12
  );

INSERT INTO
  INSTRUCTOR (INSTRUCTOR_ID, PROFESSOR_ID, ACTIVITY_ID)
VALUES
  (
    NEXTVAL('INSTRUCTOR_SEQ'),
    8,
    13
  );

INSERT INTO
  INSTRUCTOR (INSTRUCTOR_ID, PROFESSOR_ID, ACTIVITY_ID)
VALUES
  (
    NEXTVAL('INSTRUCTOR_SEQ'),
    8,
    14
  );

INSERT INTO
  INSTRUCTOR (INSTRUCTOR_ID, PROFESSOR_ID, ACTIVITY_ID)
VALUES
  (
    NEXTVAL('INSTRUCTOR_SEQ'),
    8,
    15
  );

INSERT INTO
  INSTRUCTOR (INSTRUCTOR_ID, PROFESSOR_ID, ACTIVITY_ID)
VALUES
  (
    NEXTVAL('INSTRUCTOR_SEQ'),
    9,
    16
  );

INSERT INTO
  INSTRUCTOR (INSTRUCTOR_ID, PROFESSOR_ID, ACTIVITY_ID)
VALUES
  (
    NEXTVAL('INSTRUCTOR_SEQ'),
    10,
    16
  );

INSERT INTO
  INSTRUCTOR (INSTRUCTOR_ID, PROFESSOR_ID, ACTIVITY_ID)
VALUES
  (
    NEXTVAL('INSTRUCTOR_SEQ'),
    11,
    16
  );

INSERT INTO
  INSTRUCTOR (INSTRUCTOR_ID, PROFESSOR_ID, ACTIVITY_ID)
VALUES
  (
    NEXTVAL('INSTRUCTOR_SEQ'),
    12,
    16
  );

INSERT INTO
  INSTRUCTOR (INSTRUCTOR_ID, PROFESSOR_ID, ACTIVITY_ID)
VALUES
  (
    NEXTVAL('INSTRUCTOR_SEQ'),
    9,
    17
  );

INSERT INTO
  INSTRUCTOR (INSTRUCTOR_ID, PROFESSOR_ID, ACTIVITY_ID)
VALUES
  (
    NEXTVAL('INSTRUCTOR_SEQ'),
    10,
    18
  );

INSERT INTO
  INSTRUCTOR (INSTRUCTOR_ID, PROFESSOR_ID, ACTIVITY_ID)
VALUES
  (
    NEXTVAL('INSTRUCTOR_SEQ'),
    11,
    19
  );

INSERT INTO
  INSTRUCTOR (INSTRUCTOR_ID, PROFESSOR_ID, ACTIVITY_ID)
VALUES
  (
    NEXTVAL('INSTRUCTOR_SEQ'),
    1,
    20
  );

INSERT INTO
  INSTRUCTOR (INSTRUCTOR_ID, PROFESSOR_ID, ACTIVITY_ID)
VALUES
  (
    NEXTVAL('INSTRUCTOR_SEQ'),
    7,
    21
  );

INSERT INTO
  INSTRUCTOR (INSTRUCTOR_ID, PROFESSOR_ID, ACTIVITY_ID)
VALUES
  (
    NEXTVAL('INSTRUCTOR_SEQ'),
    7,
    22
  );

INSERT INTO
  INSTRUCTOR (INSTRUCTOR_ID, PROFESSOR_ID, ACTIVITY_ID)
VALUES
  (
    NEXTVAL('INSTRUCTOR_SEQ'),
    8,
    23
  );

INSERT INTO
  INSTRUCTOR (INSTRUCTOR_ID, PROFESSOR_ID, ACTIVITY_ID)
VALUES
  (
    NEXTVAL('INSTRUCTOR_SEQ'),
    8,
    24
  );

INSERT INTO
  INSTRUCTOR (INSTRUCTOR_ID, PROFESSOR_ID, ACTIVITY_ID)
VALUES
  (
    NEXTVAL('INSTRUCTOR_SEQ'),
    9,
    24
  );

INSERT INTO
  INSTRUCTOR (INSTRUCTOR_ID, PROFESSOR_ID, ACTIVITY_ID)
VALUES
  (
    NEXTVAL('INSTRUCTOR_SEQ'),
    8,
    25
  );

INSERT INTO
  INSTRUCTOR (INSTRUCTOR_ID, PROFESSOR_ID, ACTIVITY_ID)
VALUES
  (
    NEXTVAL('INSTRUCTOR_SEQ'),
    9,
    26
  );

INSERT INTO
  INSTRUCTOR (INSTRUCTOR_ID, PROFESSOR_ID, ACTIVITY_ID)
VALUES
  (
    NEXTVAL('INSTRUCTOR_SEQ'),
    9,
    27
  );

INSERT INTO
  INSTRUCTOR (INSTRUCTOR_ID, PROFESSOR_ID, ACTIVITY_ID)
VALUES
  (
    NEXTVAL('INSTRUCTOR_SEQ'),
    10,
    28
  );

INSERT INTO
  INSTRUCTOR (INSTRUCTOR_ID, PROFESSOR_ID, ACTIVITY_ID)
VALUES
  (
    NEXTVAL('INSTRUCTOR_SEQ'),
    41,
    29
  );

INSERT INTO
  INSTRUCTOR (INSTRUCTOR_ID, PROFESSOR_ID, ACTIVITY_ID)
VALUES
  (
    NEXTVAL('INSTRUCTOR_SEQ'),
    20,
    30
  );

INSERT INTO
  INSTRUCTOR (INSTRUCTOR_ID, PROFESSOR_ID, ACTIVITY_ID)
VALUES
  (
    NEXTVAL('INSTRUCTOR_SEQ'),
    21,
    30
  );

INSERT INTO
  INSTRUCTOR (INSTRUCTOR_ID, PROFESSOR_ID, ACTIVITY_ID)
VALUES
  (
    NEXTVAL('INSTRUCTOR_SEQ'),
    22,
    30
  );

INSERT INTO
  INSTRUCTOR (INSTRUCTOR_ID, PROFESSOR_ID, ACTIVITY_ID)
VALUES
  (
    NEXTVAL('INSTRUCTOR_SEQ'),
    21,
    31
  );

INSERT INTO
  INSTRUCTOR (INSTRUCTOR_ID, PROFESSOR_ID, ACTIVITY_ID)
VALUES
  (
    NEXTVAL('INSTRUCTOR_SEQ'),
    26,
    32
  );

INSERT INTO
  INSTRUCTOR (INSTRUCTOR_ID, PROFESSOR_ID, ACTIVITY_ID)
VALUES
  (
    NEXTVAL('INSTRUCTOR_SEQ'),
    26,
    33
  );

INSERT INTO
  INSTRUCTOR (INSTRUCTOR_ID, PROFESSOR_ID, ACTIVITY_ID)
VALUES
  (
    NEXTVAL('INSTRUCTOR_SEQ'),
    26,
    34
  );

INSERT INTO
  INSTRUCTOR (INSTRUCTOR_ID, PROFESSOR_ID, ACTIVITY_ID)
VALUES
  (
    NEXTVAL('INSTRUCTOR_SEQ'),
    27,
    35
  );

INSERT INTO
  INSTRUCTOR (INSTRUCTOR_ID, PROFESSOR_ID, ACTIVITY_ID)
VALUES
  (
    NEXTVAL('INSTRUCTOR_SEQ'),
    31,
    36
  );

INSERT INTO
  INSTRUCTOR (INSTRUCTOR_ID, PROFESSOR_ID, ACTIVITY_ID)
VALUES
  (
    NEXTVAL('INSTRUCTOR_SEQ'),
    31,
    37
  );

INSERT INTO
  INSTRUCTOR (INSTRUCTOR_ID, PROFESSOR_ID, ACTIVITY_ID)
VALUES
  (
    NEXTVAL('INSTRUCTOR_SEQ'),
    32,
    38
  );

INSERT INTO
  INSTRUCTOR (INSTRUCTOR_ID, PROFESSOR_ID, ACTIVITY_ID)
VALUES
  (
    NEXTVAL('INSTRUCTOR_SEQ'),
    34,
    39
  );

INSERT INTO
  INSTRUCTOR (INSTRUCTOR_ID, PROFESSOR_ID, ACTIVITY_ID)
VALUES
  (
    NEXTVAL('INSTRUCTOR_SEQ'),
    6,
    40
  );

INSERT INTO
  INSTRUCTOR (INSTRUCTOR_ID, PROFESSOR_ID, ACTIVITY_ID)
VALUES
  (
    NEXTVAL('INSTRUCTOR_SEQ'),
    6,
    41
  );

INSERT INTO
  INSTRUCTOR (INSTRUCTOR_ID, PROFESSOR_ID, ACTIVITY_ID)
VALUES
  (
    NEXTVAL('INSTRUCTOR_SEQ'),
    6,
    42
  );

INSERT INTO
  INSTRUCTOR (INSTRUCTOR_ID, PROFESSOR_ID, ACTIVITY_ID)
VALUES
  (
    NEXTVAL('INSTRUCTOR_SEQ'),
    6,
    43
  );

INSERT INTO
  INSTRUCTOR (INSTRUCTOR_ID, PROFESSOR_ID, ACTIVITY_ID)
VALUES
  (
    NEXTVAL('INSTRUCTOR_SEQ'),
    6,
    44
  );

INSERT INTO
  INSTRUCTOR (INSTRUCTOR_ID, PROFESSOR_ID, ACTIVITY_ID)
VALUES
  (
    NEXTVAL('INSTRUCTOR_SEQ'),
    6,
    45
  );

INSERT INTO
  INSTRUCTOR (INSTRUCTOR_ID, PROFESSOR_ID, ACTIVITY_ID)
VALUES
  (
    NEXTVAL('INSTRUCTOR_SEQ'),
    6,
    46
  );

INSERT INTO
  INSTRUCTOR (INSTRUCTOR_ID, PROFESSOR_ID, ACTIVITY_ID)
VALUES
  (
    NEXTVAL('INSTRUCTOR_SEQ'),
    6,
    47
  );

INSERT INTO
  INSTRUCTOR (INSTRUCTOR_ID, PROFESSOR_ID, ACTIVITY_ID)
VALUES
  (
    NEXTVAL('INSTRUCTOR_SEQ'),
    6,
    48
  );

INSERT INTO
  INSTRUCTOR (INSTRUCTOR_ID, PROFESSOR_ID, ACTIVITY_ID)
VALUES
  (
    NEXTVAL('INSTRUCTOR_SEQ'),
    6,
    49
  );

INSERT INTO
  INSTRUCTOR (INSTRUCTOR_ID, PROFESSOR_ID, ACTIVITY_ID)
VALUES
  (
    NEXTVAL('INSTRUCTOR_SEQ'),
    6,
    50
  );
