\i ./s-04-dml-diploma.sql
\i ./s-04-dml-division.sql
\i ./s-04-dml-work-position.sql
\i ./s-04-dml-department.sql
\i ./s-04-dml-administrator.sql
\i ./s-04-dml-venue.sql
\i ./s-04-dml-professor.sql
\i ./s-04-dml-activity_catalogue.sql
\i ./s-04-dml-activity.sql
\i ./s-04-dml-instructor.sql
\i ./s-04-dml-participant.sql
\i ./s-04-dml-activity-evaluation.sql