\qecho ================== INSERTING INTO INSTRUCTOR ==================

INSERT INTO
  INSTRUCTOR (INSTRUCTOR_ID, PROFESSOR_ID, ACTIVITY_ID)
VALUES
  (
    NEXTVAL('INSTRUCTOR_SEQ'),
    29,
    1
  );

INSERT INTO
  INSTRUCTOR (INSTRUCTOR_ID, PROFESSOR_ID, ACTIVITY_ID)
VALUES
  (
    NEXTVAL('INSTRUCTOR_SEQ'),
    30,
    1
  );

INSERT INTO
  INSTRUCTOR (INSTRUCTOR_ID, PROFESSOR_ID, ACTIVITY_ID)
VALUES
  (
    NEXTVAL('INSTRUCTOR_SEQ'),
    47,
    2
  );

INSERT INTO
  INSTRUCTOR (INSTRUCTOR_ID, PROFESSOR_ID, ACTIVITY_ID)
VALUES
  (
    NEXTVAL('INSTRUCTOR_SEQ'),
    35,
    2
  );

INSERT INTO
  INSTRUCTOR (INSTRUCTOR_ID, PROFESSOR_ID, ACTIVITY_ID)
VALUES
  (
    NEXTVAL('INSTRUCTOR_SEQ'),
    46,
    3
  );  